from __future__ import annotations


LOCAL_TRUST_MUTANT_CASES = (
    (
        "local-explicit-authorization-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(payload.get("explicit_user_authorization") is True, "invalid-local-receipt")',
        '_require(True, "invalid-local-receipt")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_missing_explicit_authorization_or_caveat_is_rejected",
    ),
    (
        "local-external-key-path-check-disabled",
        "scripts/local_controlled_path_safety.py",
        'def is_within(path: Path, root: Path) -> bool:\n    try:\n        path.relative_to(root)\n        return True\n    except ValueError:\n        return False',
        'def is_within(path: Path, root: Path) -> bool:\n    return False',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_unknown_or_project_replaced_public_key_is_rejected",
    ),
    (
        "local-owned-symlink-check-disabled",
        "scripts/local_controlled_path_safety.py",
        "if resolved != path:",
        "if False:",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_owned_paths_reject_signed_and_expected_aliases",
    ),
    (
        "local-owned-hardlink-check-disabled",
        "scripts/local_controlled_path_safety.py",
        "return value_stat.st_nlink == 1",
        "return True",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_owned_paths_reject_signed_and_expected_aliases",
    ),
    (
        "local-ledger-time-validation-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_parse_utc(expires_at, "invalid-replay-state")',
        "datetime.now(timezone.utc)",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_guard_rejects_invalid_ledger_entries",
    ),
    (
        "local-ledger-receipt-identity-validation-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(IDENTITY_RE.fullmatch(receipt_id) is not None, "invalid-replay-state")',
        '_require(True, "invalid-replay-state")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_guard_rejects_invalid_ledger_entries",
    ),
    (
        "local-ledger-nonce-validation-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(SHA256_RE.fullmatch(nonce) is not None, "invalid-replay-state")',
        '_require(True, "invalid-replay-state")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_guard_rejects_invalid_ledger_entries",
    ),
    (
        "local-ledger-global-uniqueness-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(receipt_id not in receipt_ids and nonce not in nonces,\n                     "invalid-replay-state")',
        '_require(True, "invalid-replay-state")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_guard_rejects_invalid_ledger_entries",
    ),
    (
        "local-replay-independent-identity-disabled",
        "scripts/local_controlled_trust_validation.py",
        'receipt_id in {item["receipt_id"] for item in consumed}\n                    or nonce in {item["nonce"] for item in consumed}',
        'receipt_id in {item["receipt_id"] for item in consumed}\n                    and nonce in {item["nonce"] for item in consumed}',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_receipt_id_and_nonce_are_independently_single_use",
    ),
    (
        "local-ordinary-module-lease-enabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(receipt_type == "system_governance_bootstrap", "invalid-local-receipt")',
        '_require(True, "invalid-local-receipt")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_same_user_mode_rejects_ordinary_module_write_lease",
    ),
    (
        "local-post-bootstrap-host-native-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(payload.get("post_bootstrap_authority") == "host-native-module-lease-required",\n             "invalid-local-receipt")',
        '_require(True, "invalid-local-receipt")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_bootstrap_cannot_self_report_follow_on_lease_authority",
    ),
    (
        "local-replay-consumption-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(replay_guard.consume(receipt_id, nonce, expires_at), "replayed-receipt")',
        '_require(True, "replayed-receipt")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_valid_explicit_local_bootstrap_is_accepted_once",
    ),
    (
        "local-detached-signature-verification-disabled",
        "scripts/local_controlled_trust_validation.py",
        'public_key.verify(raw, DOMAIN.encode("utf-8") + b"\\0" + canonical)',
        'return',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_invalid_detached_signature_is_rejected",
    ),
    (
        "local-expiry-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(current < expires, "receipt-expired")',
        '_require(True, "receipt-expired")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_expired_or_not_yet_valid_receipt_is_rejected",
    ),
    (
        "local-replay-lock-link-uniqueness-disabled",
        "scripts/local_controlled_path_safety.py",
        "and opened.st_nlink == 1\n        and named.st_nlink == 1",
        "and True",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_lock_rejects_symlink_directory_and_hardlink",
    ),
    (
        "local-replay-lock-inode-race-check-disabled",
        "scripts/local_controlled_path_safety.py",
        "and (opened.st_dev, opened.st_ino) == (named.st_dev, named.st_ino)",
        "and True",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_lock_inode_swap_after_open_is_rejected",
    ),
    (
        "local-missing-artifact-stable-error-disabled",
        "scripts/local_controlled_path_safety.py",
        'def resolve_strict(path: Path, code: str) -> Path:\n    try:\n        return path.resolve(strict=True)\n    except (OSError, RuntimeError) as error:\n        raise LocalControlledTrustError(code) from error',
        'def resolve_strict(path: Path, code: str) -> Path:\n    try:\n        return path.resolve(strict=True)\n    except (OSError, RuntimeError) as error:\n        raise error',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_missing_external_artifacts_return_stable_cli_json",
    ),
    (
        "local-ledger-boolean-schema-alias-enabled",
        "scripts/local_controlled_trust_validation.py",
        'type(value.get("schema_version")) is int\n                 and value.get("schema_version") == 1',
        'value.get("schema_version") == 1',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_schema_versions_reject_boolean_aliases",
    ),
    (
        "local-envelope-boolean-schema-alias-enabled",
        "scripts/local_controlled_trust_validation.py",
        'type(envelope.get("schema_version")) is int\n             and envelope.get("schema_version") == 1',
        'envelope.get("schema_version") == 1',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_schema_versions_reject_boolean_aliases",
    ),
    (
        "local-payload-boolean-schema-alias-enabled",
        "scripts/local_controlled_trust_validation.py",
        'type(payload.get("schema_version")) is int\n             and payload.get("schema_version") == 1',
        'payload.get("schema_version") == 1',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_schema_versions_reject_boolean_aliases",
    ),
    (
        "local-unsupported-receipt-type-json-check-disabled",
        "scripts/validate_local_controlled_trust.py",
        'if arguments.receipt_type != "system_governance_bootstrap":',
        "if False:",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_cli_rejects_unsupported_receipt_type_with_json_error",
    ),
    (
        "local-signature-canonical-base64url-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(len(raw) == 64 and encoded == canonical_value, "invalid-local-signature")',
        '_require(len(raw) == 64, "invalid-local-signature")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_noncanonical_detached_signature_encoding_is_rejected",
    ),
    (
        "local-bootstrap-template-relative-path-restored",
        "assets/system-governance-bootstrap-receipt.template.json",
        "{{EXACT_CANONICAL_ABSOLUTE_OWNED_PATH}}",
        "{{EXACT_EXTERNAL_AUTHORIZED_PROJECT_RELATIVE_PATH}}",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_bootstrap_template_and_schema_use_absolute_owned_paths",
    ),
    (
        "local-bootstrap-schema-absolute-path-check-disabled",
        "assets/system-governance-bootstrap-receipt.schema.json",
        '"owned_paths": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"type": "string", "minLength": 1, "pattern": "^/"}}',
        '"owned_paths": {"type": "array", "minItems": 1, "uniqueItems": true, "items": {"type": "string", "minLength": 1}}',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_bootstrap_template_and_schema_use_absolute_owned_paths",
    ),
    (
        "local-signature-schema-length-form-relaxed",
        "assets/local-controlled-detached-signature.schema.json",
        '"pattern": "^[A-Za-z0-9_-]{85}[AQgw]$"',
        '"pattern": "^[A-Za-z0-9_-]+$"',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_bootstrap_template_and_schema_use_absolute_owned_paths",
    ),
    (
        "local-replay-parent-directory-fsync-disabled",
        "scripts/local_controlled_file_safety.py",
        "fsync_directory(path.parent, expected_parent_identity)",
        "None",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_state_fsyncs_parent_directory_after_atomic_replace",
    ),
    (
        "local-replay-parent-identity-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        "_require(current_identity == self._parent_identity, \"unsafe-replay-parent-path\")",
        "_require(True, \"unsafe-replay-parent-path\")",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_guard_rejects_parent_directory_replacement",
    ),
    (
        "local-owned-path-exact-case-check-disabled",
        "scripts/local_controlled_path_safety.py",
        "if not path.is_absolute() or not has_exact_path_spelling(path):",
        "if not path.is_absolute():",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_owned_path_rejects_case_insensitive_spelling_alias",
    ),
    (
        "local-project-root-exact-case-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        'def _validation_root(project_root: Path, receipt_type: str) -> Path:\n    root = _canonical_directory(project_root, "project-root-mismatch")',
        'def _validation_root(project_root: Path, receipt_type: str) -> Path:\n    root = project_root.resolve(strict=True)',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_project_root_rejects_case_insensitive_spelling_alias",
    ),
    (
        "local-external-artifact-exact-case-check-disabled",
        "scripts/local_controlled_path_safety.py",
        "from local_controlled_file_safety import has_exact_path_spelling",
        "has_exact_path_spelling = lambda path: True",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_external_artifacts_and_replay_reject_case_insensitive_spelling_aliases",
    ),
    (
        "local-replay-state-exact-case-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        'if initial_state is not None and stat.S_ISREG(initial_state.st_mode):\n            _require(has_exact_path_spelling(self._state_path), "unsafe-replay-state-path")',
        'if False:\n            _require(has_exact_path_spelling(self._state_path), "unsafe-replay-state-path")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_external_artifacts_and_replay_reject_case_insensitive_spelling_aliases",
    ),
    (
        "local-replay-opened-ledger-identity-check-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(opened_identity == identity, "unsafe-replay-state-path")',
        '_require(True, "unsafe-replay-state-path")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_ledger_swap_between_path_check_and_read_cannot_clear_history",
    ),
    (
        "local-replay-ledger-identity-recheck-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(self._current_state_identity() == expected, "unsafe-replay-state-path")',
        '_require(True, "unsafe-replay-state-path")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_ledger_inode_swap_after_read_is_rejected",
    ),
    (
        "local-broken-symlink-ledger-treated-as-absent",
        "scripts/local_controlled_trust_validation.py",
        '_require(\n            stat.S_ISREG(value.st_mode) and value.st_nlink == 1,\n            "unsafe-replay-state-path",\n        )\n        return value.st_dev, value.st_ino',
        'if not stat.S_ISREG(value.st_mode):\n            return None\n        _require(value.st_nlink == 1, "unsafe-replay-state-path")\n        return value.st_dev, value.st_ino',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_broken_symlink_replay_ledger_is_rejected_without_consumption",
    ),
    (
        "local-missing-argv-json-error-disabled",
        "scripts/validate_local_controlled_trust.py",
        "except ValueError:\n        print(json.dumps({\"valid\": False, \"error\": \"invalid-cli-arguments\"}, sort_keys=True))\n        return 1",
        "except RuntimeError:\n        print(json.dumps({\"valid\": False, \"error\": \"invalid-cli-arguments\"}, sort_keys=True))\n        return 1",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_cli_missing_required_arguments_use_stable_json_error",
    ),
    (
        "local-replay-parent-fsync-fd-identity-check-disabled",
        "scripts/local_controlled_file_safety.py",
        "and (opened.st_dev, opened.st_ino) == expected_identity",
        "and True",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_replay_parent_fsync_fd_must_match_frozen_parent_identity",
    ),
    (
        "local-path-resolve-runtime-error-mapping-disabled",
        "scripts/local_controlled_path_safety.py",
        "except (OSError, RuntimeError) as error:\n        raise LocalControlledTrustError(code) from error",
        "except OSError as error:\n        raise LocalControlledTrustError(code) from error",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_symlink_loop_runtime_errors_return_stable_cli_json",
    ),
    (
        "local-cli-runtime-error-json-mapping-disabled",
        "scripts/validate_local_controlled_trust.py",
        "except (OSError, RuntimeError):\n        print(json.dumps({\"valid\": False, \"error\": \"local-trust-io-error\"}, sort_keys=True))",
        "except OSError:\n        print(json.dumps({\"valid\": False, \"error\": \"local-trust-io-error\"}, sort_keys=True))",
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_symlink_loop_runtime_errors_return_stable_cli_json",
    ),
    (
        "local-signed-replay-state-binding-disabled",
        "scripts/local_controlled_trust_validation.py",
        '_require(payload.get("replay_state_path") == str(replay_guard.state_path),\n             "replay-state-mismatch")',
        '_require(True, "replay-state-mismatch")',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_signed_replay_state_path_prevents_cross_ledger_reuse",
    ),
    (
        "local-bootstrap-schema-replay-state-binding-disabled",
        "assets/system-governance-bootstrap-receipt.schema.json",
        '"project_root", "replay_state_path", "owned_paths"',
        '"project_root", "owned_paths"',
        "scripts.test_local_controlled_trust.LocalControlledTrustTests.test_bootstrap_template_and_schema_use_absolute_owned_paths",
    ),
)
