from __future__ import annotations


WRITE_AUTHORITY_MUTANT_CASES = (
    (
        "hierarchy-dispatch-write-override-check-disabled",
        "scripts/agents_dispatcher_policy_validation.py",
        "            or _weakens_module_closure(segments) or hierarchy_write_override(segments)\n",
        "            or _weakens_module_closure(segments) or False\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_agent_hierarchy_cannot_grant_write_without_lease",
    ),
    (
        "maintainer-black-box-own-work-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "black[ -]?box(?:\\s+tests?)?|",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "maintainer-acceptance-testing-own-work-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "acceptance\\s+tests?|acceptance\\s+testing|",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "maintainer-adjudication-own-work-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "adjudicat(?:e|es|ed|ing|or|ors|ion|ions)|",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "maintainer-adjudicator-nominalization-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "adjudicat(?:e|es|ed|ing|or|ors|ion|ions)|",
        "adjudicat(?:e|es|ed|ing)|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_actor_and_gate_action_matrix_cannot_self_validate",
    ),
    (
        "other-module-maintainer-writer-actor-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "r\"\\b(?:another|other)\\s+module\\s+maintainers?\\b|其他模块维护\\s*Agent|\"",
        "r\"unused-other-module-maintainer|\"",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_write_authority_actor_action_object_matrix",
    ),
    (
        "another-actor-negation-word-boundary-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "    return bool(re.search(r\"\\bread[ -]?only\\b|只读|不得|不可|禁止|无权\", segment[actor.end():end], re.IGNORECASE))\n",
        "    return bool(re.search(r\"不得|不可|禁止|无权\", segment[actor.end():end], re.IGNORECASE))\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_read_only_role_mention_does_not_poison_canonical_writer_binding",
    ),
    (
        "maintainer-chinese-black-box-own-work-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "裁决|黑盒测试|",
        "裁决|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "authorized-writer-self-signoff-actor-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "implementers?|authorized writers?|lease[ -]?holders?)",
        "implementers?|lease[ -]?holders?)",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "lease-holder-self-signoff-actor-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "implementers?|authorized writers?|lease[ -]?holders?)",
        "implementers?|authorized writers?)",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_writer_cannot_execute_its_own_independent_gates",
    ),
    (
        "module-work-product-target-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "artifacts?|tests?|files?|code|records?|module|project|",
        "code|records?|module|project|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_noncanonical_actor_cannot_write_any_module_work_product",
    ),
    (
        "module-implementation-action-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"implement(?:s|ed|ing)?|updat(?:e|es|ed|ing)|record(?:s|ed|ing)?|\"\n",
        "    r\"updat(?:e|es|ed|ing)|record(?:s|ed|ing)?|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_noncanonical_actor_cannot_write_any_module_work_product",
    ),
    (
        "hard-deny-writer-actor-priority-disabled",
        "scripts/write_authority_policy_validation.py",
        "    rf\"(?P<canonical>{CANONICAL_WRITER_ACTOR})\", re.IGNORECASE,\n",
        "    rf\"(?P<canonical>{CANONICAL_WRITER_ACTOR})|(?P<hard>unused-hard-deny)\", re.IGNORECASE,\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_noncanonical_actor_cannot_borrow_canonical_lease_language",
    ),
    (
        "canonical-writer-actor-proof-disabled",
        "scripts/write_authority_policy_validation.py",
        "        CANONICAL_WRITER_ACTOR,\n",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_hierarchy_writer_exception_is_exact_target_and_owned_path_bound",
    ),
    (
        "safe-independent-result-record-exception-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    safe_records = _safe_independent_result_spans(scope)\n",
        "    safe_records = ()\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_gate_result_recording_is_record_only",
    ),
    (
        "record-only-post-result-execution-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "        if any(start <= match.start() and match.end() <= end for start, end in safe_records):\n",
        "        if True:\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_gate_result_recording_is_record_only",
    ),
    (
        "canonical-independent-role-writer-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "    rf\"\\bDispatcher\\b|{INDEPENDENT_ROLE}|{CANONICAL_READ_ONLY_ROLE}|\"\n",
        "    rf\"\\bDispatcher\\b|{INDEPENDENT_ROLE}|unused-read-only-role|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_all_canonical_independent_roles_are_read_only_writers",
    ),
    (
        "hierarchy-forbidden-target-scope-check-disabled",
        "scripts/write_authority_policy_validation.py",
        "    return not re.search(FORBIDDEN_SCOPE, text, re.IGNORECASE) and all(\n",
        "    return all(\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_hierarchy_writer_exception_is_exact_target_and_owned_path_bound",
    ),
    (
        "hierarchy-exact-target-proof-disabled",
        "scripts/write_authority_policy_validation.py",
        "        r\"exact\\s+(?:current\\s+)?module\\s+target|本模块(?:的)?精确目标\",\n",
        "        r\"(?:exact\\s+)?owned paths?|(?:精确)?所有权路径\",\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_hierarchy_writer_exception_is_exact_target_and_owned_path_bound",
    ),
    (
        "self-signoff-continuation-actor-inheritance-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "            segment = \"The module maintainer \" + segment\n",
        "            segment = segment\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_result_recording_does_not_hide_other_self_signoff_actions",
    ),
    (
        "independent-gate-execution-action-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "|execut(?:e|es|ed|ing)|run(?:s|ning)?|done)\\b|\"",
        "|done)\\b|\"",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_result_recording_does_not_hide_other_self_signoff_actions",
    ),
    (
        "review-result-recording-gate-equivalence-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    r\"(?:\\b(?:review|black[ -]?box|adjudication|acceptance)[ -]+(?:result|verdict)\\b|\"\n",
        "    r\"(?:\\b(?:black[ -]?box|adjudication|acceptance)[ -]+(?:result|verdict)\\b|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_gate_result_recording_is_record_only",
    ),
    (
        "generic-independent-role-grammar-disabled",
        "scripts/write_authority_policy_validation.py",
        "    rf\"\\bDispatcher\\b|{INDEPENDENT_ROLE}|{CANONICAL_READ_ONLY_ROLE}|\"\n",
        "    rf\"\\bDispatcher\\b|{CANONICAL_READ_ONLY_ROLE}|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_role_write_ontology_and_segment_inheritance",
    ),
    (
        "write-mutation-action-ontology-disabled",
        "scripts/write_authority_policy_validation.py",
        "    rf\"\\b{ENGLISH_WRITE_ACTION}\\b|写入|修改|实现|更新|记录|登记|追加|创建|删除|覆盖|\"\n",
        "    rf\"\\b{ENGLISH_WRITE_ACTION}\\b|写入|修改|实现|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_role_write_ontology_and_segment_inheritance",
    ),
    (
        "write-actor-segment-inheritance-disabled",
        "scripts/write_authority_policy_validation.py",
        "            segment = f\"{previous_actor} {segment}\"\n",
        "            segment = segment\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_role_write_ontology_and_segment_inheritance",
    ),
    (
        "normalized-forbidden-scope-grammar-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"(?:another|different|other|sibling)\\s+module|cross[ -]?module|\"\n",
        "    r\"another\\s+module|cross[ -]?module|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_hierarchy_scope_and_negation_grammar_is_fail_closed",
    ),
    (
        "canonical-implementation-writer-proof-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"\\bcurrent\\s+canonical\\s+(?:module\\s+maintainer|implementation\\s+(?:Agent|writer))\\b|\"\n",
        "    r\"\\bcurrent\\s+canonical\\s+(?:module\\s+maintainer|implementation\\s+Agent)\\b|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_role_write_ontology_and_segment_inheritance",
    ),
    (
        "write-negation-authorization-grammar-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"(?P<negative>\\bnot\\s+(?:allowed|authorized|permitted)(?:\\s+to)?\\b|\"\n",
        "    r\"(?P<negative>unused-negative-authorization|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_hierarchy_scope_and_negation_grammar_is_fail_closed",
    ),
    (
        "self-signoff-modal-segment-inheritance-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "            r\"(?:then|and|while|may|can|allowed|permitted|authorized|然后|并|同时|可|可以|允许)\",\n",
        "            r\"(?:then|and|while|然后|并|同时)\",\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_segment_inheritance_and_gate_action_ontology",
    ),
    (
        "release-publish-verdict-action-ontology-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    r\"\\b(?:publish(?:es|ed|ing)?|releas(?:e|es|ed|ing)|issu(?:e|es|ed|ing)\\s+\"\n",
        "    r\"unused-release-publish-verdict|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_segment_inheritance_and_gate_action_ontology",
    ),
    (
        "independently-passed-order-and-hyphen-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    r\"(?:\\bindependently[ -]+passed\\b|\\bpassed\\s+independently\\b|(?:已经|已)?独立通过)\", re.IGNORECASE,\n",
        "    r\"(?:\\bindependently\\s+passed\\b|(?:已经|已)?独立通过)\", re.IGNORECASE,\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_segment_inheritance_and_gate_action_ontology",
    ),
    (
        "canonical-writer-complete-proof-enforcement-disabled",
        "scripts/write_authority_policy_validation.py",
        "        if controlled and not _legal_writer_implementation(segment):\n",
        "        if False and controlled and not _legal_writer_implementation(segment):\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_canonical_writer_requires_complete_proof_and_excludes_coordinated_reviewers",
    ),
    (
        "coordinated-hard-deny-writer-enforcement-disabled",
        "scripts/write_authority_policy_validation.py",
        "        if any(actor.lastgroup == \"hard\" and not _actor_is_read_only(segment, actor, relevant)\n",
        "        if False and any(actor.lastgroup == \"hard\" and not _actor_is_read_only(segment, actor, relevant)\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_canonical_writer_requires_complete_proof_and_excludes_coordinated_reviewers",
    ),
    (
        "patch-replace-remove-write-action-ontology-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"patch(?:es|ed|ing)?|replac(?:e|es|ed|ing)|remov(?:e|es|ed|ing)|\"\n",
        "    r\"unused-new-write-actions|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_write_actor_discourse_and_action_clause_polarity",
    ),
    (
        "writer-pronoun-discourse-inheritance-disabled",
        "scripts/write_authority_policy_validation.py",
        "        rf\"\\s*(?:(?:it|they|该角色|其)\\s*)?(?:remains?\\b[^,;。；]{{0,30}}|\"\n",
        "        rf\"\\s*(?:remains?\\b[^,;。；]{{0,30}}|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_write_actor_discourse_and_action_clause_polarity",
    ),
    (
        "per-action-write-negation-disabled",
        "scripts/write_authority_policy_validation.py",
        "        if _action_is_negated(grant_prefix):\n",
        "        if False and _action_is_negated(grant_prefix):\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_write_actor_discourse_and_action_clause_polarity",
    ),
    (
        "writer-proof-contradiction-enforcement-disabled",
        "scripts/write_authority_policy_validation.py",
        "    return not re.search(FORBIDDEN_SCOPE, text, re.IGNORECASE) and all(\n",
        "    return all(\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_canonical_writer_requires_complete_proof_and_excludes_coordinated_reviewers",
    ),
    (
        "final-acceptance-verdict-self-signoff-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    r\"(?:(?:a|its own|the final acceptance)\\s+)?verdict|final\\s+approval)\\b|\"\n",
        "    r\"(?:(?:a|its own)\\s+)?verdict|final\\s+approval)\\b|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_passive_nominal_and_pronoun_ontology",
    ),
    (
        "self-signoff-pronoun-discourse-inheritance-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "            r\"\\s*(?:(?:it|they|its|their|该角色|其)\\s*)?\"\n",
        "            r\"\\s*\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_passive_nominal_and_pronoun_ontology",
    ),
    (
        "result-of-acceptance-review-safe-record-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "    r\"\\b(?:result|verdict)\\s+of\\s+(?:the\\s+)?(?:acceptance\\s+)?review\\b|\"\n",
        "    r\"unused-result-of-review|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_signoff_passive_nominal_and_pronoun_ontology",
    ),
    (
        "chinese-coordinator-hard-deny-actor-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"协调者(?=\\s*(?:可|可以|允许|有权|不得|不能|不可|只读|，|,|。|；|;))\"\n",
        "    r\"unused-chinese-coordinator\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_chinese_coordinator_is_a_hard_deny_writer_actor",
    ),
    (
        "write-irregular-and-progressive-inflections-disabled",
        "scripts/write_authority_policy_validation.py",
        "    r\"(?:writ(?:e|es|ing|ten)|wrote|modif(?:y|ies|ied|ying)|edit(?:s|ted|ting)?|\"\n",
        "    r\"(?:write|modify|edit|\"\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_write_action_inflections_share_the_authority_ontology",
    ),
    (
        "safe-result-optional-article-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "(?:result|verdict)\\s+of\\s+(?:the\\s+)?(?:acceptance\\s+)?review",
        "(?:result|verdict)\\s+of\\s+(?:acceptance\\s+)?review",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_safe_result_record_accepts_optional_article_in_review_relation",
    ),
)
