from __future__ import annotations


REVIEW_FIX_MUTANT_CASES = (
    (
        "browser-url-scheme-check-disabled", "scripts/browser_url_validation.py",
        '        parsed.scheme.casefold() in {"http", "https"}\n',
        "        bool(parsed.scheme)\n",
        "scripts.test_browser_url_validation.BrowserUrlValidationTests.test_file_credentials_and_nonstandard_urls_are_rejected",
    ),
    (
        "local-http-preview-policy-check-disabled", "scripts/agents_delivery_policy_validation.py",
        "def _has_local_http_preview_policy(section: str) -> bool:\n    return _section_has_line(section, (\n",
        "def _has_local_http_preview_policy(section: str) -> bool:\n    return True or _section_has_line(section, (\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_local_browser_pages_require_http_preview_not_file_scheme",
    ),
    (
        "frontend-page-url-transcript-binding-disabled", "scripts/validate_frontend_evidence.py",
        '            or data.get("page_url") != value.get("page_url")\n',
        "",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_browser_page_url_must_match_hashed_transcript",
    ),
    (
        "swimlane-page-url-transcript-binding-disabled", "scripts/validate_swimlane_evidence.py",
        '            or data.get("page_url") != raw_browser.get("page_url")):\n',
        "):\n",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_swimlane_page_url_must_match_hashed_transcript",
    ),
    (
        "global-policy-contradiction-check-disabled", "scripts/agents_policy_validation.py",
        "    issues.extend(_validate_global_policy_contradictions(text))\n",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_global_or_section_override_cannot_disable_machine_gates",
    ),
    (
        "context-baseline-cache-binding-disabled", "scripts/validate_context_manifest.py",
        '        metadata.get("Baseline artifact", ""),\n        metadata.get("Baseline version", ""),\n        metadata.get("Baseline SHA-256", "").casefold(),\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_baseline_change_invalidates_cache_key",
    ),
    (
        "trace-role-artifact-reuse-check-disabled", "scripts/validate_traceability.py",
        "if previous_role is None or previous_role == column:",
        "if True:",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_different_trace_roles_cannot_all_reuse_baseline_artifact",
    ),
    (
        "implementation-frontend-evidence-check-disabled", "scripts/validate_delivery_bundle.py",
        "    return command_applicable or trace_applicable\n",
        '    return stage == "completion" and (command_applicable or trace_applicable)\n',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_implementation_stage_missing_frontend_evidence_is_blocked",
    ),
    (
        "delivery-requirement-subset-check-disabled", "scripts/validate_delivery_bundle.py",
        "if not context_ids or not context_ids <= trace_ids:",
        "if trace_ids != context_ids:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_context_requirement_ids_may_select_current_trace_subset",
    ),
    (
        "module-run-owned-files-check-disabled", "scripts/delivery_record_validation.py",
        "def _module_changed_files(context: dict[str, str], module: str) -> str:\n",
        'def _module_changed_files(context: dict[str, str], module: str) -> str:\n    return context.get("Changed files", "")\n',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_changed_files_use_module_ownership_map",
    ),
    (
        "commands-template-deep-check-disabled", "scripts/validate_project_commands.py",
        "        _validate_template_commands(data, issues)\n",
        "",
        "scripts.test_validate_project_commands.ProjectCommandValidatorTests.test_template_mode_rejects_nested_unsafe_command",
    ),
    (
        "frontend-template-deep-check-disabled", "scripts/validate_frontend_evidence.py",
        '        issues.extend(Issue("error", code, message) for code, message in _frontend_template_issues(\n            data, BROWSER_FIELDS, E2E_FIELDS, PLACEHOLDER_RE,\n        ))\n',
        "",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_template_mode_rejects_invalid_nested_browser_and_e2e",
    ),
    (
        "swimlane-template-deep-check-disabled", "scripts/validate_swimlane_evidence.py",
        '        issues.extend(Issue("error", code, message) for code, message in _swimlane_template_issues(\n            data, DIAGRAM_FIELDS, BROWSER_FIELDS,\n        ))\n',
        "",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_template_mode_rejects_invalid_nested_diagram_and_browser",
    ),
    (
        "multi-agent-template-deep-check-disabled", "scripts/validate_multi_agent_evidence.py",
        '        issues.extend(Issue("error", code, message) for code, message in _multi_agent_template_issues(data, GATE_FIELDS))\n',
        "",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_public_template_structure_passes_and_rejects_nested_gate_bypass",
    ),
    (
        "context-template-deep-check-disabled", "scripts/validate_context_manifest.py",
        "        issues.extend(_validate_template_values(metadata))\n",
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_template_mode_rejects_unsafe_run_and_invalid_module_map",
    ),
    (
        "trace-template-deep-check-disabled", "scripts/validate_traceability.py",
        "        issues.extend(validate_template_tables(tables[0], tables[1], tables[2], tables[3]))\n",
        "",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_template_mode_rejects_wrong_role_id_and_status",
    ),
    (
        "frontend-declared-action-coverage-disabled", "scripts/frontend_state_validation.py",
        "return all(observed[action] for action in ranks) and all(\n        observed[action] == targets[action] for action in ranks\n    )",
        'return all(observed[action] for action in ranks) and observed["click"] == targets["click"]',
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_transcript_actions_cover_every_declared_assertion_and_screenshot",
    ),
    (
        "agents-missing-file-json-check-disabled", "scripts/validate_agents_md.py",
        "    if not arguments.json:\n        raise SystemExit(message)\n",
        "    if True:\n        raise SystemExit(message)\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_missing_file_json_mode_returns_structured_issue",
    ),
    (
        "requirement-code-workset-binding-disabled", "scripts/trace_workset_binding.py",
        "    if not changed or not code_artifacts or any(not _covered(path, code_artifacts) for path in changed):\n",
        "    if False:\n",
        "scripts.test_trace_workset_binding.TraceWorksetBindingTests.test_selected_requirement_must_cover_current_changed_files",
    ),
    (
        "module-requirement-attribution-disabled", "scripts/trace_workset_binding.py",
        '        result[module] = ", ".join(sorted(ids))\n',
        '        result[module] = context.get("Requirement IDs", "")\n',
        "scripts.test_trace_workset_binding.TraceWorksetBindingTests.test_module_records_receive_only_owned_requirement_ids",
    ),
    (
        "trace-content-copy-reuse-check-disabled", "scripts/validate_traceability.py",
        "    previous_role = artifact_roles.get(identity) or artifact_content_roles.get(digest)\n",
        "    previous_role = artifact_roles.get(identity)\n",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_distinct_role_paths_cannot_copy_identical_artifact_content",
    ),
    (
        "global-discretionary-validator-check-disabled", "scripts/agents_policy_validation.py",
        '        r"(?:all|every|全部|所有).{0,40}(?:validators?|gates?|checks?|验证器|门禁|检查).{0,80}(?:discretionary|optional|need\\s+not|not\\s+required|可选|无需|不必)",\n',
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_global_completion_authority_cannot_make_all_validators_discretionary",
    ),
    (
        "password-authorization-duplicate-check-disabled", "scripts/agents_policy_validation.py",
        "    if duplicates:\n",
        "    if False:\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_password_authorization_rejects_casefold_duplicate_fields",
    ),
    (
        "frontend-template-e2e-type-check-disabled", "scripts/template_schema_validation.py",
        '        issues.append(("invalid-e2e-field-types", "模板 E2E 身份、时间、框架和路径必须是非空字符串"))\n',
        "        pass\n",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_template_mode_rejects_e2e_object_types_and_malformed_mobile",
    ),
    (
        "frontend-template-mobile-check-disabled", "scripts/template_schema_validation.py",
        '            issues.append(("invalid-mobile-template", "模板 mobile 必须是单一占位符、N/A 原因或完整 browser 对象"))\n',
        "            pass\n",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_template_mode_rejects_e2e_object_types_and_malformed_mobile",
    ),
    (
        "multi-template-open-disagreement-check-disabled", "scripts/template_schema_validation.py",
        '        issues.append(("open-agent-disagreement", "模板 open_disagreements 必须为空"))\n',
        "        pass\n",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_public_template_structure_passes_and_rejects_nested_gate_bypass",
    ),
    (
        "context-template-baseline-path-check-disabled", "scripts/validate_context_manifest.py",
        '        issues.append(Issue("error", "unsafe-baseline-artifact", "模板 Baseline artifact 必须是安全项目相对路径"))\n',
        "        pass\n",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_template_mode_rejects_unsafe_baseline_path_and_reuse",
    ),
    (
        "context-template-reuse-check-disabled", "scripts/validate_context_manifest.py",
        '        issues.append(Issue("error", "invalid-template-reuse", "公共模板不得预先复用未绑定当前基线的旧证据"))\n',
        "        pass\n",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_template_mode_rejects_unsafe_baseline_path_and_reuse",
    ),
    (
        "trace-template-gate-check-disabled", "scripts/trace_template_validation.py",
        "        *_gate_issues(gate_rows, gate_numbers),\n",
        "",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_template_mode_rejects_optional_or_failed_required_gate",
    ),
    (
        "trace-content-whitespace-normalization-disabled", "scripts/validate_traceability.py",
        '        lines = [line.rstrip(" \\t") for line in visible.splitlines()]\n',
        "        lines = visible.splitlines()\n",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_trace_role_content_copy_cannot_hide_with_whitespace_changes",
    ),
    (
        "nonfrontend-user-visible-applicability-check-disabled", "scripts/validate_delivery_bundle.py",
        '    trace_applicable = bool(surfaces & {"ui", "mobile", "touch", "responsive"})\n',
        '    trace_applicable = bool(surfaces & {"ui", "user-visible", "mobile", "touch", "responsive"})\n',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_nonfrontend_user_visible_change_does_not_require_browser_evidence",
    ),
    (
        "module-owned-requirement-template-check-disabled", "assets/execution-run.template.md",
        "- Traceability IDs: {{MODULE_OWNED_REQUIREMENT_IDS}}\n",
        "- Traceability IDs: {{REQ_FLOW_FEAT_UI_UT_AT_MOD_BB_IDS}}\n",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_execution_run_template_uses_module_owned_requirement_ids",
    ),
    (
        "trace-zero-width-format-normalization-disabled", "scripts/validate_traceability.py",
        '        visible = "".join(character for character in normalized if unicodedata.category(character) != "Cf")\n',
        "        visible = normalized\n",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_trace_role_content_copy_cannot_hide_with_zero_width_format_chars",
    ),
    (
        "trace-internal-whitespace-semantics-disabled", "scripts/validate_traceability.py",
        '        lines = [line.rstrip(" \\t") for line in visible.splitlines()]\n        canonical = "\\n".join(lines).strip("\\n").encode("utf-8")\n',
        '        canonical = re.sub(r"\\s+", " ", visible).strip().encode("utf-8")\n',
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_trace_content_identity_preserves_internal_whitespace_semantics",
    ),
    (
        "frontend-command-applicability-authority-disabled", "scripts/validate_delivery_bundle.py",
        "    return command_applicable or trace_applicable\n",
        "    return trace_applicable\n",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_frontend_internal_change_uses_command_applicability",
    ),
    (
        "external-loop-hash-round-binding-check-disabled",
        "scripts/agents_delivery_policy_validation.py",
        'r"six rounds|6 rounds|六轮|6 轮", r"incomplete|未完成",\n                r"hash|SHA-256|哈希", r"bundle|聚合|门禁",',
        'r"six rounds|6 rounds|六轮|6 轮",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_external_loop_cannot_omit_hash_gate_or_six_round_incomplete_stop",
    ),
    (
        "native-agent-provider-boundary-check-disabled",
        "scripts/validate_multi_agent_evidence.py",
        'elif gate.get("provider") not in {"independent-agent", "codex-native-agent"}:',
        "elif False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_external_model_cannot_satisfy_native_black_box_gate",
    ),
    (
        "external-multi-model-contradiction-check-disabled",
        "scripts/agents_delivery_policy_validation.py",
        'if any(re.search(pattern, flattened, re.IGNORECASE) for pattern in contradiction_patterns):',
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_external_multi_model_roles_cannot_be_negated_or_obsolete",
    ),
)
