from __future__ import annotations

ADDITIONAL_MUTANT_CASES = (
    (
        "trace-table-separator-check-disabled", "scripts/traceability_parsing.py",
        'not re.fullmatch(r":?-{3,}:?", value) for value in separator',
        "False for value in separator",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_table_separator_cannot_hide_pending_requirement",
    ),
    (
        "context-requirement-id-cache-binding-disabled", "scripts/validate_context_manifest.py",
        'requirement_ids = ",".join(sorted(\n        item.strip().casefold()\n        for item in metadata.get("Requirement IDs", "").split(",")\n        if item.strip()\n    ))',
        'requirement_ids = ""',
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_requirement_ids_change_invalidates_cache_key",
    ),
    (
        "delivery-requirement-id-binding-disabled", "scripts/validate_delivery_bundle.py",
        "if not context_ids or not context_ids <= trace_ids:", "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_context_requirement_ids_must_match_trace",
    ),
    (
        "declared-record-required-fields-check-disabled", "scripts/delivery_record_io.py",
        'if any(not fields.get(field.casefold(), "").strip() for field in required):', "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_missing_plan_semantics_blocks_delivery",
    ),
    (
        "declared-record-stage-check-disabled", "scripts/delivery_record_io.py",
        "if allowed_statuses is not None and status not in allowed_statuses:", "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_implementation_stage_rejects_completed_progress",
    ),
    (
        "progress-open-work-check-disabled", "scripts/delivery_record_io.py",
        'if closed_field and fields.get(closed_field.casefold(), "").casefold() not in CLOSED_VALUES[closed_field.casefold()]:', "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_completion_rejects_open_remaining_work",
    ),
    (
        "delivery-automated-review-policy-binding-disabled", "scripts/agents_delivery_policy_validation.py",
        'r"baseline/code/build", r"review/frontend",',
        'r"baseline/code/build", r"frontend",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_delivery_bundle_must_bind_automated_review_record",
    ),
    (
        "delivery-module-log-policy-binding-disabled", "scripts/agents_delivery_policy_validation.py",
        'r"contract", r"trace", r"plan/progress", r"current run",',
        'r"contract", r"trace", r"plan/progress",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_delivery_bundle_must_bind_module_run_and_latest",
    ),
    (
        "module-latest-completion-gate-disabled", "scripts/delivery_record_validation.py",
        'if stage != "completion":\n        return issues',
        'if True:\n        return issues',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_missing_module_latest_blocks_completion",
    ),
    (
        "module-latest-record-binding-disabled", "scripts/delivery_record_validation.py",
        '                       "Record": run_path',
        "",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_latest_must_link_current_run_record",
    ),
    (
        "module-latest-swimlane-binding-disabled", "scripts/delivery_record_validation.py",
        '        latest_expected["Swimlane evidence"] = evidence_paths.get("Swimlane evidence", "")',
        "        pass",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_latest_must_bind_current_swimlane_evidence",
    ),
    (
        "automated-review-record-gate-disabled", "scripts/delivery_record_validation.py",
        'issues = _validate_record(\n        path, root, "automated-review",',
        'issues = [] if path else _validate_record(\n        path, root, "automated-review",',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_missing_automated_review_evidence_blocks_delivery",
    ),
    (
        "automated-review-open-findings-check-disabled", "scripts/delivery_record_validation.py",
        '{"pass"}, "Findings",', '{"pass"}, None,',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_open_automated_review_finding_blocks_delivery",
    ),
    (
        "module-run-review-evidence-binding-disabled", "scripts/delivery_record_validation.py",
        '        "Automated review evidence": _review_path(text), **evidence_paths,\n',
        '        **evidence_paths,\n',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_must_bind_declared_evidence_paths",
    ),
    (
        "progress-current-run-index-binding-disabled", "scripts/delivery_record_validation.py",
        'expected = {"Modules": ", ".join(modules), "Module run records": run_links}',
        'expected = {"Modules": ", ".join(modules)}',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_progress_index_must_link_current_module_run",
    ),
    (
        "module-run-stage-check-disabled", "scripts/delivery_record_validation.py",
        'statuses = {"completed"} if stage == "completion" else {"pending", "in_progress", "blocked"}',
        'statuses = {"completed", "pending", "in_progress", "blocked"}',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_implementation_stage_rejects_completed_module_run",
    ),
    (
        "module-run-open-risk-check-disabled", "scripts/delivery_record_validation.py",
        'statuses, "Remaining risks" if stage == "completion" else None)', "statuses, None)",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_completion_rejects_open_module_risks",
    ),
    (
        "automated-review-execution-result-check-disabled", "scripts/delivery_record_validation.py",
        "if (not _review_scope_valid(fields, planned_command_ids) or not _review_trigger_valid(fields)\n            or not _review_execution_valid(\n                fields, command_manifest_path, root, planned_command_ids,\n            )):",
        "if (not _review_scope_valid(fields, planned_command_ids) or not _review_trigger_valid(fields)):",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_unexecuted_automated_review_cannot_claim_pass",
    ),
    (
        "declared-record-nul-check-disabled", "scripts/delivery_record_io.py",
        'if b"\\x00" in payload:', "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_declared_records_reject_real_nul_bytes",
    ),
    (
        "context-stable-run-id-check-disabled", "scripts/validate_context_manifest.py",
        'if not STABLE_ID_RE.fullmatch(metadata["Run ID"]):', "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_run_id_must_be_a_stable_path_segment",
    ),
    (
        "delivery-stable-run-id-check-disabled", "scripts/delivery_record_validation.py",
        "if not STABLE_ID_RE.fullmatch(run_id):", "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_run_id_cannot_escape_module_log_directory",
    ),
    (
        "context-stable-module-id-check-disabled", "scripts/validate_context_manifest.py",
        "if not modules or len(modules) != len(set(modules)) or any(not STABLE_ID_RE.fullmatch(item) for item in modules):", "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_module_ids_must_be_stable_path_segments",
    ),
    (
        "delivery-stable-module-id-check-disabled", "scripts/delivery_record_validation.py",
        "if not raw_modules or any(not STABLE_ID_RE.fullmatch(item) for item in raw_modules):",
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_id_cannot_escape_module_log_directory",
    ),
    (
        "declared-record-casefold-duplicate-check-disabled", "scripts/delivery_record_io.py",
        "field, value = match.group(1).strip().casefold(), match.group(2).strip()",
        "field, value = match.group(1).strip(), match.group(2).strip()",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_declared_records_reject_casefold_duplicates_and_hidden_content",
    ),
    (
        "declared-record-unexpected-content-check-disabled", "scripts/delivery_record_io.py",
        "if unexpected or unknown:", "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_declared_records_reject_unknown_open_fields",
    ),
    (
        "field-specific-closed-semantics-disabled", "scripts/delivery_record_io.py",
        '"findings": {"none", "closed", "no actionable findings", "无", "无可执行问题"},',
        '"findings": {"none", "closed", "no actionable findings", "no remaining work", "无", "无可执行问题"},',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_closed_semantics_are_field_specific",
    ),
    (
        "declared-record-parent-symlink-check-disabled", "scripts/delivery_record_io.py",
        "if candidate.is_absolute() or _has_symlink_component(resolved_root, candidate) or not resolved.is_file():",
        "if candidate.is_absolute() or not resolved.is_file():",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_record_parent_symlink_is_rejected",
    ),
    (
        "declared-record-hardlink-alias-check-disabled", "scripts/delivery_record_validation.py",
        "if identity in identities:", "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_and_latest_cannot_share_hardlink",
    ),
    (
        "review-command-argv-binding-disabled", "scripts/delivery_record_validation.py",
        'if fields.get("review command argv sha-256", "") != _argv_hash(review.get("argv")):',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_command_hash_must_bind_command_manifest",
    ),
    (
        "review-output-hash-binding-disabled", "scripts/delivery_record_validation.py",
        'if hashlib.sha256(payload).hexdigest() != fields.get("review evidence sha-256", "").casefold():',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_output_hash_must_bind_existing_artifact",
    ),
    (
        "review-output-structured-transcript-check-disabled", "scripts/delivery_record_validation.py",
        "except (UnicodeError, json.JSONDecodeError, ValueError):\n        return False",
        "except (UnicodeError, json.JSONDecodeError, ValueError):\n        return True",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_evidence_requires_structured_transcript",
    ),
    (
        "review-output-changed-file-alias-check-disabled", "scripts/delivery_record_validation.py",
        'if _aliases_changed_file(resolved, fields.get("changed files", ""), root):',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_evidence_cannot_reuse_changed_source_file",
    ),
    (
        "module-run-current-evidence-path-binding-disabled", "scripts/delivery_record_validation.py",
        "if not _record_paths_include(run_path, root, required_paths):",
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_records_must_bind_current_verification_paths",
    ),
    (
        "module-latest-current-evidence-path-binding-disabled", "scripts/delivery_record_validation.py",
        'if not _record_paths_include(latest_path, root, {"Verification evidence": latest_verification}):',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_records_must_bind_current_verification_paths",
    ),
    (
        "review-transcript-unknown-fields-check-disabled", "scripts/delivery_record_validation.py",
        "if not isinstance(data, dict) or set(data) != required_keys:",
        "if not isinstance(data, dict):",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_rejects_unknown_failure_fields",
    ),
    (
        "review-transcript-bool-integer-check-disabled", "scripts/delivery_record_validation.py",
        'if type(data.get("schema_version")) is not int or type(data.get("exit_code")) is not int:',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_rejects_boolean_integer_aliases",
    ),
    (
        "review-transcript-bool-rerun-check-disabled", "scripts/delivery_record_validation.py",
        "if not isinstance(reruns, dict) or any(type(value) is not int for value in reruns.values()):",
        "if not isinstance(reruns, dict):",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_rejects_boolean_rerun_results",
    ),
    (
        "module-record-extra-evidence-path-check-disabled", "scripts/delivery_record_validation.py",
        'if not required or "" in required or required != tokens:',
        'if not required or "" in required or not required <= tokens:',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_records_reject_extra_fake_evidence_paths",
    ),
    (
        "review-transcript-duplicate-json-key-check-disabled", "scripts/delivery_record_validation.py",
        'json.loads(payload.decode("utf-8"), object_pairs_hook=_unique_json_object)',
        'json.loads(payload.decode("utf-8"))',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_rejects_duplicate_json_keys",
    ),
    (
        "declared-record-hidden-heading-check-disabled", "scripts/delivery_record_io.py",
        "            else:\n                unexpected.append(line)\n            continue",
        "            else:\n                continue\n            continue",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_declared_records_reject_hidden_open_headings",
    ),
    (
        "review-transcript-changed-files-binding-disabled", "scripts/delivery_record_validation.py",
        '"changed_files": sorted(item.strip() for item in fields.get("changed files", "").split(",") if item.strip()),',
        '"changed_files": data.get("changed_files"),',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_binds_changed_files",
    ),
    (
        "review-transcript-code-fingerprint-binding-disabled", "scripts/delivery_record_validation.py",
        '"code_fingerprint": fields.get("code fingerprint"),',
        '"code_fingerprint": data.get("code_fingerprint"),',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_binds_code_fingerprint",
    ),
    (
        "review-transcript-command-manifest-binding-disabled", "scripts/delivery_record_validation.py",
        '"command_manifest_fingerprint": fields.get("command manifest fingerprint"),',
        '"command_manifest_fingerprint": data.get("command_manifest_fingerprint"),',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_transcript_binds_command_manifest_fingerprint",
    ),
    (
        "module-run-baseline-binding-disabled", "scripts/delivery_record_validation.py",
        '        "Baseline version and SHA-256": f\'{trace.get("Baseline version", "")} / {trace.get("Baseline SHA-256", "")}\',\n',
        "",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_binds_baseline",
    ),
    (
        "module-run-build-binding-disabled", "scripts/delivery_record_validation.py",
        '        "Build ID and acceptance environment": f\'{trace.get("Build ID", "")} / {trace.get("Acceptance environment", "")}\',\n',
        "",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_binds_build_and_environment",
    ),
    (
        "module-run-context-binding-disabled", "scripts/delivery_record_validation.py",
        '        "Context workset manifest and reused evidence fingerprints": (\n            f\'{_relative_path(context_path, root)} / {context.get("Evidence cache key", "")}\'\n        ),\n',
        "",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_binds_context_manifest_and_cache",
    ),
    (
        "module-run-risk-binding-disabled", "scripts/delivery_record_validation.py",
        '        "Risk level and reason": context.get("Risk / expansion reason", ""),\n',
        "",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_run_binds_risk_level_and_reason",
    ),
    (
        "record-heading-identity-binding-disabled", "scripts/delivery_record_io.py",
        '        return rf"(?:Run|执行)\\s+{value}" if value else None',
        '        return r"(?:Run|执行)\\s+\\S+"',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_record_headings_bind_run_and_module",
    ),
    (
        "automated-review-scope-binding-disabled", "scripts/delivery_record_validation.py",
        "if (not _review_scope_valid(fields, planned_command_ids) or not _review_trigger_valid(fields)\n            or not _review_execution_valid(\n                fields, command_manifest_path, root, planned_command_ids,\n            )):",
        "if (not _review_trigger_valid(fields)\n            or not _review_execution_valid(\n                fields, command_manifest_path, root, planned_command_ids,\n            )):",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_scope_must_cover_changed_files_and_dependency_surfaces",
    ),
    (
        "context-risk-binding-disabled", "scripts/validate_delivery_bundle.py",
        'if (any(not part for part in expected_risk) or len(context_risk) != 3\n            or context_risk[:2] != expected_risk or not context_risk[2]):',
        "if False:",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_context_risk_must_bind_trace_risk",
    ),
    (
        "context-module-file-map-check-disabled", "scripts/validate_context_manifest.py",
        'if set().union(*mapping.values()) != changed:',
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_module_changed_files_must_map_every_changed_file",
    ),
    (
        "context-module-map-cache-binding-disabled", "scripts/validate_context_manifest.py",
        '        _canonical_module_file_map(metadata.get("Module changed files", "")),\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_module_file_map_change_invalidates_cache_key",
    ),
    (
        "swimlane-module-ownership-check-disabled", "scripts/validate_swimlane_evidence.py",
        "elif evidence_paths != expected_evidence:",
        "elif False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_two_modules_require_distinct_correctly_owned_diagrams",
    ),
    (
        "swimlane-diagram-inode-uniqueness-disabled", "scripts/validate_swimlane_evidence.py",
        "if identity in identities:",
        "if False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_diagram_roles_cannot_share_path_or_hardlink",
    ),
    (
        "agent-artifact-inode-uniqueness-disabled", "scripts/validate_multi_agent_evidence.py",
        "if identity in artifact_identities:",
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_hardlinked_outputs_cannot_claim_independent_evidence",
    ),
    (
        "agent-output-workset-isolation-disabled", "scripts/validate_multi_agent_evidence.py",
        'if path_field == "output_evidence" and identity in forbidden_outputs:',
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_agent_output_cannot_reuse_changed_source",
    ),
    (
        "agent-output-provenance-check-disabled", "scripts/validate_multi_agent_evidence.py",
        '            if path_field == "output_evidence":\n                _validate_gate_output(resolved, role, gate, evidence, issues)',
        "",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_agent_output_must_bind_role_run_and_verdict",
    ),
    (
        "swimlane-flow-trigger-policy-check-disabled", "scripts/agents_delivery_policy_validation.py",
        'r"(?:flow_impact=|if )`?changed|flow_impact.*changed", r"stabili[sz]ed candidate|稳定候选", r"batch|合并|批", r"at most once|至多.*一次", r"first downstream consumer|首次.*下游"',
        'r".*", r".*", r".*", r".*", r".*"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_swimlane_changed_flow_is_batched_per_stabilized_candidate",
    ),
    (
        "swimlane-update-negation-check-disabled", "scripts/agents_delivery_policy_validation.py",
        "if _required_swimlane_update_negated(section):",
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_swimlane_required_updates_cannot_be_negated",
    ),
    (
        "swimlane-overfrequency-conflict-check-disabled", "scripts/agents_delivery_policy_validation.py",
        "if _section_has_line(section, forced_internal):",
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_flow_neutral_edits_cannot_force_swimlane_redraws",
    ),
    (
        "module-file-unique-ownership-check-disabled", "scripts/validate_context_manifest.py",
        "if raw_path in raw_owners or identity in owners:",
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_module_file_ownership_rejects_overlap_and_path_aliases",
    ),
    (
        "review-scope-trailing-nonexecution-check-disabled", "scripts/delivery_record_validation.py",
        "if re.search(negative, scope):",
        "if re.match(negative, scope):",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_review_scope_cannot_hide_nonexecution_after_valid_categories",
    ),
    (
        "agent-artifact-content-uniqueness-check-disabled", "scripts/validate_multi_agent_evidence.py",
        "if digest in artifact_hashes:",
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_inputs_must_not_reuse_identical_content",
    ),
    (
        "agent-provider-focus-type-check-disabled", "scripts/validate_multi_agent_evidence.py",
        'if any(not isinstance(gate.get(field), str) or not gate.get(field, "").strip() for field in ("provider", "focus")):',
        'if any(not str(gate.get(field, "")).strip() for field in ("provider", "focus")):',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_provider_and_focus_must_be_nonempty_strings",
    ),
    (
        "swimlane-trigger-optional-weakening-check-disabled", "scripts/agents_delivery_policy_validation.py",
        "if _swimlane_trigger_weakened(section):",
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_swimlane_required_triggers_cannot_be_optional",
    ),
    (
        "module-dot-path-alias-check-disabled", "scripts/validate_context_manifest.py",
        'if candidate.is_absolute() or raw_path != candidate.as_posix() or ".." in candidate.parts:',
        'if candidate.is_absolute() or ".." in candidate.parts:',
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_single_module_rejects_dot_path_alias",
    ),
    (
        "duplicate-module-id-check-disabled", "scripts/validate_context_manifest.py",
        "len(modules) != len(set(modules)) or ",
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_duplicate_module_ids_are_rejected",
    ),
    (
        "agent-run-id-string-type-check-disabled", "scripts/native_gate_agent_validation.py",
        'identity = value.strip() if isinstance(value, str) else ""',
        'identity = str(value or "").strip()',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_agent_run_id_must_be_a_string",
    ),
    (
        "agent-input-semantic-whitespace-check-disabled", "scripts/validate_multi_agent_evidence.py",
        'normalized = "\\n".join(line.rstrip() for line in text.splitlines()).strip()',
        'normalized = text',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_inputs_cannot_bypass_content_reuse_with_whitespace",
    ),
    (
        "agent-input-allowed-paths-check-disabled", "scripts/multi_agent_input_validation.py",
        "if len(paths) != len(set(paths)) or set(paths) - allowed_paths:",
        "if len(paths) != len(set(paths)):",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_input_rejects_full_chat_or_unrelated_paths",
    ),
    (
        "agent-input-required-role-artifacts-check-disabled", "scripts/multi_agent_input_validation.py",
        "if allowed_paths - set(paths):",
        "if False and allowed_paths - set(paths):",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_input_requires_all_role_specific_artifacts",
    ),
    (
        "agent-input-artifact-hash-check-disabled", "scripts/multi_agent_input_validation.py",
        "if hashlib.sha256(current.read_bytes()).hexdigest() != hash_value.casefold():",
        "if False and hashlib.sha256(current.read_bytes()).hexdigest() != hash_value.casefold():",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_input_artifact_hash_detects_post_capture_drift",
    ),
    (
        "multi-agent-bool-schema-check-disabled", "scripts/validate_multi_agent_evidence.py",
        'if type(schema_version) is not int or schema_version not in {1, 2}:',
        'if schema_version not in {1, 2}:',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_boolean_schema_version_is_rejected",
    ),
    (
        "swimlane-bool-schema-check-disabled", "scripts/validate_swimlane_evidence.py",
        'if type(data.get("schema_version")) is not int or data.get("schema_version") != 1:',
        'if data.get("schema_version") != 1:',
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_boolean_schema_version_is_rejected",
    ),
    (
        "frontend-bool-schema-check-disabled", "scripts/validate_frontend_evidence.py",
        'if type(data.get("schema_version")) is not int or data.get("schema_version") != 1:',
        'if data.get("schema_version") != 1:',
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_boolean_schema_version_is_rejected",
    ),
    (
        "commands-bool-schema-check-disabled", "scripts/validate_project_commands.py",
        'if type(data.get("schema_version")) is not int or data.get("schema_version") != 1:',
        'if data.get("schema_version") != 1:',
        "scripts.test_validate_project_commands.ProjectCommandValidatorTests.test_boolean_schema_version_is_rejected",
    ),
    (
        "multi-agent-top-level-duplicate-key-check-disabled", "scripts/validate_multi_agent_evidence.py",
        'def _read_json(path: Path) -> tuple[dict[str, object] | None, list[Issue]]:\n    try:\n        data = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_unique_object)',
        'def _read_json(path: Path) -> tuple[dict[str, object] | None, list[Issue]]:\n    try:\n        data = json.loads(path.read_text(encoding="utf-8"))',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_top_level_and_gate_unknown_or_duplicate_fields_fail_closed",
    ),
    (
        "multi-agent-top-level-exact-fields-check-disabled", "scripts/validate_multi_agent_evidence.py",
        "if set(data) != expected_fields:",
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_top_level_and_gate_unknown_or_duplicate_fields_fail_closed",
    ),
    (
        "multi-agent-gate-exact-fields-check-disabled", "scripts/validate_multi_agent_evidence.py",
        "if set(raw) != GATE_FIELDS:",
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_top_level_and_gate_unknown_or_duplicate_fields_fail_closed",
    ),
    (
        "agent-input-exclusion-bool-type-check-disabled", "scripts/multi_agent_input_validation.py",
        'or any(type(data.get(field)) is not bool for field in (\n                "includes_full_chat", "includes_other_agent_reasoning",\n                "includes_implementation_self_report",\n            ))',
        'or any(data.get(field) not in (False,) for field in (\n                "includes_full_chat", "includes_other_agent_reasoning",\n                "includes_implementation_self_report",\n            ))',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_role_input_exclusion_flags_must_be_json_booleans",
    ),
    (
        "agent-input-requirement-filter-check-disabled", "scripts/validate_multi_agent_evidence.py",
        "if requirement_ids and not requirement_ids & row_ids:",
        "if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_trace_role_paths_only_include_current_requirement_ids",
    ),
    (
        "agent-output-input-manifest-binding-disabled", "scripts/validate_multi_agent_evidence.py",
        '"input_sha256": gate.get("input_sha256"), "verdict": "pass", "findings": [],',
        '"input_sha256": data.get("input_sha256"), "verdict": "pass", "findings": [],',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_agent_output_binds_exact_input_manifest_hash",
    ),
    (
        "frontend-viewport-bool-alias-check-disabled", "scripts/validate_frontend_evidence.py",
        "any(type(item) is not int or item <= 0 for item in viewport)",
        "any(not isinstance(item, int) or item <= 0 for item in viewport)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_viewport_and_e2e_counts_reject_boolean_integer_aliases",
    ),
    (
        "frontend-e2e-count-bool-alias-check-disabled", "scripts/validate_frontend_evidence.py",
        "any(type(item) is not int for item in numeric)",
        "any(not isinstance(item, int) for item in numeric)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_viewport_and_e2e_counts_reject_boolean_integer_aliases",
    ),
    ("missing-agent-artifact-early-return-disabled", "scripts/validate_multi_agent_evidence.py",
        'issues.append(Issue("error", "missing-agent-artifact", f"{role} 证据不存在：{raw_path}"))\n        return None',
        'issues.append(Issue("error", "missing-agent-artifact", f"{role} 证据不存在：{raw_path}"))',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_missing_input_or_output_returns_structured_issue_without_crash"),
)
