from __future__ import annotations


STABILITY_MUTANT_CASES = (
    ("normative-html-comment-stripping-disabled", "scripts/agents_policy_common.py",
     "    return HTML_COMMENT_RE.sub(_blank_match, text)\n", "    return text\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_html_comment_policy_text_cannot_satisfy_normative_rule"),
    ("normative-fenced-code-stripping-disabled", "scripts/agents_policy_common.py",
     "        if match:\n            fence = match.group(\"fence\")\n",
     "        if False and match:\n            fence = match.group(\"fence\")\n",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fenced_policy_text_cannot_satisfy_normative_rule"),
    ("record-path-exactly-once-check-disabled", "scripts/delivery_record_paths.py",
     "    return values[0] if len(values) == 1 else None\n", "    return values[0] if values else None\n",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_duplicate_path_declarations_fail_closed"),
    ("review-scope-path-label-confusion", "scripts/delivery_record_paths.py",
     "(?:Automated review evidence path|自动审查证据路径)",
     "(?:Automated review evidence path|Review scope|自动审查证据路径)",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_review_scope_is_not_a_review_evidence_path_declaration"),
    ("system-cross-module-record-parent-alias-check-disabled",
        "scripts/system_record_path_validation.py",
        '            and all(part not in {".", ".."} for part in candidate.parts)\n',
        '            and all(part not in {"."} for part in candidate.parts)\n',
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_cross_module_record_templates_reject_parent_traversal",
    ),
    (
        "system-cross-module-record-component-isolation-check-disabled",
        "scripts/system_record_path_validation.py",
        "            and module_parts[0] != run_parts[0])",
        "            and True)",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_cross_module_record_placeholders_require_separate_components",
    ),
    (
        "system-cross-module-progress-record-mapping-disabled",
        "scripts/system_record_path_validation.py",
        '        "进度记录": declared_path(\n'
        '            plan_section, PROGRESS_RECORD_PATH,\n'
        '        ),\n',
        "",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_cross_module_aggregation_rejects_shared_progress_path",
    ),
    (
        "system-cross-module-review-record-mapping-disabled",
        "scripts/system_record_path_validation.py",
        '        "自动审查证据": declared_path(\n'
        '            review_section, AUTOMATED_REVIEW_EVIDENCE_PATH,\n'
        '        ),\n',
        "",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_cross_module_aggregation_rejects_shared_review_path",
    ),
    (
        "browser-page-url-artifact-binding-disabled", "scripts/browser_page_validation.py",
        "if expected_hash != actual_hash or url_path != served_path:",
        "if expected_hash != actual_hash:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_browser_page_url_must_identify_current_served_artifact",
    ),
    (
        "swimlane-system-page-artifact-binding-disabled", "scripts/browser_page_validation.py",
        'if expected_path is not None and str(evidence["page_artifact_path"]) != expected_path:',
        "if False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_swimlane_browser_cannot_serve_module_diagram_as_system_overview",
    ),
    (
        "browser-observed-response-binding-disabled", "scripts/browser_page_validation.py",
        "if live_hash != observed_hash or live_hash != actual_hash:",
        "if live_hash != actual_hash:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_browser_observed_response_must_match_current_entry_artifact",
    ),
    (
        "swimlane-loopback-page-binding-disabled", "scripts/browser_page_validation.py",
        "if require_loopback and not _loopback_host(parsed_url.hostname):",
        "if False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_swimlane_page_url_must_serve_current_system_diagram",
    ),
    (
        "implementation-black-box-not-started-check-disabled", "scripts/validate_traceability.py",
        'if not black_box_not_started(row):',
        "if False:",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_implementation_stage_rejects_started_black_box",
    ),
    (
        "workset-leaf-symlink-check-disabled", "scripts/validate_context_manifest.py",
        "if (root / candidate).is_symlink():",
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_symlinked_workset_leaf_cannot_hide_scoped_agents",
    ),
    (
        "context-risk-cache-binding-disabled", "scripts/validate_context_manifest.py",
        '        metadata.get("Risk / expansion reason", ""),\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_risk_and_dependency_boundaries_invalidate_cache_key",
    ),
    (
        "context-dependency-cache-binding-disabled", "scripts/validate_context_manifest.py",
        '        metadata.get("Direct dependency boundaries", ""),\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_risk_and_dependency_boundaries_invalidate_cache_key",
    ),
    (
        "context-build-id-cache-binding-disabled", "scripts/validate_context_manifest.py",
        '        metadata.get("Build ID", ""),\n', "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_build_id_changes_invalidate_cache",
    ),
    (
        "multi-module-reuse-rerun-check-disabled", "scripts/validate_context_manifest.py",
        "if len(modules) != 1:\n        issues.append(Issue(\n            \"error\", \"multi-module-reuse-requires-rerun\",",
        "if False:\n        issues.append(Issue(\n            \"error\", \"multi-module-reuse-requires-rerun\",",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_multi_module_reuse_requires_rerun",
    ),
    (
        "reuse-success-record-binding-disabled", "scripts/validate_context_manifest.py",
        "if not _valid_reuse_record_types(data) or data != expected:",
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_run_must_bind_successful_provenance_record",
    ),
    (
        "multi-requirement-cell-binding-disabled", "scripts/validate_delivery_bundle.py",
        '        for identifier, _ in LINK_RE.findall(row.get("Requirement", ""))\n',
        '        for identifier, _ in LINK_RE.findall(row.get("Requirement", ""))[:1]\n',
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_requirement_cell_may_bind_multiple_current_requirement_ids",
    ),
    (
        "browser-live-http-response-check-disabled", "scripts/browser_page_validation.py",
        "if live_hash != observed_hash or live_hash != actual_hash:",
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_authoritative_frontend_url_must_return_live_current_bytes",
    ),
    (
        "frontend-entry-authority-check-disabled", "scripts/browser_page_validation.py",
        "if expected_url is not None and (",
        "if False and (",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_browser_entry_must_match_authoritative_project_manifest",
    ),
    (
        "swimlane-drilldown-target-check-disabled", "scripts/swimlane_html_validation.py",
        "if set(parser.entries) != modules:",
        "if False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_system_drilldown_targets_must_match_current_modules",
    ),
    (
        "reuse-current-run-check-disabled", "scripts/validate_context_manifest.py",
        'if reused_run_id == metadata.get("Run ID", "").strip():',
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_current_run_cannot_reuse_itself",
    ),
    (
        "reuse-source-run-check-disabled", "scripts/validate_context_manifest.py",
        '    _validate_reuse_source_run(\n        data["source_run_record"], reused_run_id, expected["evidence_cache_key"],\n        expected_paths, metadata, root, issues,\n    )\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_must_bind_existing_successful_source_run",
    ),
    (
        "context-duplicate-requirement-check-disabled", "scripts/validate_context_manifest.py",
        "len(requirement_ids) != len(set(requirement_ids))",
        "False",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_requirement_ids_must_be_unique",
    ),
    (
        "trace-requirement-row-identity-check-disabled", "scripts/validate_traceability.py",
        "            issues.extend(requirement_identity_issues(column, links, row_number, requirement_rows))\n",
        "",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_requirement_id_cannot_be_split_across_multiple_rows",
    ),
    (
        "module-selected-requirement-intersection-disabled", "scripts/trace_workset_binding.py",
        "(_row_requirement_ids(row) & selected_ids, _row_code_paths([row], root))",
        "(_row_requirement_ids(row), _row_code_paths([row], root))",
        "scripts.test_trace_workset_binding.TraceWorksetBindingTests.test_multi_requirement_row_only_attributes_selected_ids",
    ),
    (
        "trace-template-required-gates-check-disabled", "scripts/trace_template_validation.py",
        "for gate in REQUIRED_GATES - set(gates):",
        "for gate in set():",
        "scripts.test_validate_traceability.TraceabilityValidatorTests.test_template_requires_black_box_gate",
    ),
    (
        "swimlane-malformed-diagrams-guard-disabled", "scripts/validate_swimlane_evidence.py",
        "diagrams = raw_diagrams if isinstance(raw_diagrams, list) else []",
        "diagrams = raw_diagrams",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_malformed_diagrams_fail_closed_without_exception",
    ),
    (
        "frontend-dom-action-binding-disabled", "scripts/validate_frontend_evidence.py",
        "    issues.extend(Issue(\"error\", code, message) for code, message in dom_action_issues(value, data, root))\n",
        "",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_click_and_assert_targets_must_exist_in_hashed_dom_snapshot",
    ),
    (
        "frontend-screenshot-viewport-check-disabled", "scripts/validate_frontend_evidence.py",
        "if screenshot is not None and not screenshot_covers_viewport(screenshot.read_bytes(), viewport):",
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_screenshot_pixels_must_cover_declared_viewport",
    ),
    (
        "swimlane-href-target-binding-disabled", "scripts/swimlane_html_validation.py",
        'if (parser.hidden_entries or parser.hidden_back or modules & (parser.hidden_ids | hidden_css)\n            or "@unsupported-css-import" in hidden_css\n            or any(key.startswith(("@entry:", "@back:")) for key in hidden_css)\n            or any(parser.entry_ids.get(module) in hidden_css for module in modules)\n            or any(parser.entry_tags.get(module) != "a" for module in modules)\n            or any(tag != "a" for tag in parser.back_tags)\n            or any(parser.entries[module] != f"#{module}" or module not in parser.ids for module in modules)):',
        "if False:",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_system_drilldown_controls_require_href_and_target_id",
    ),
    (
        "frontend-dom-snapshot-hash-binding-disabled", "scripts/browser_dom_validation.py",
        "if hashlib.sha256(payload).hexdigest() != raw_hash.casefold():",
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_stale_dom_snapshot_hash_is_rejected",
    ),
    (
        "frontend-dom-utf8-check-disabled", "scripts/browser_dom_validation.py",
        "except UnicodeDecodeError:",
        "except ():",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_invalid_utf8_dom_snapshot_fails_closed",
    ),
    (
        "frontend-dom-hidden-check-disabled", "scripts/browser_dom_validation.py",
        "hidden = _hidden(names, values, style) or bool(self.hidden_stack and self.hidden_stack[-1])",
        "hidden = bool(self.hidden_stack and self.hidden_stack[-1])",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_hidden_or_disabled_dom_targets_cannot_prove_interaction",
    ),
    (
        "frontend-dom-disabled-check-disabled", "scripts/browser_dom_validation.py",
        "disabled = _disabled(names, values) or bool(self.disabled_stack and self.disabled_stack[-1])",
        "disabled = bool(self.disabled_stack and self.disabled_stack[-1])",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_hidden_or_disabled_dom_targets_cannot_prove_interaction",
    ),
    (
        "frontend-png-scanline-check-disabled", "scripts/image_evidence_validation.py",
        "return (width, height) if _decoded_scanlines(compressed, expected, row_bytes, height) else None",
        "return (width, height)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_png_dimensions_must_match_decoded_scanlines",
    ),
    (
        "frontend-truncated-http-check-disabled", "scripts/browser_page_validation.py",
        ", http.client.HTTPException",
        "",
        "scripts.test_browser_page_validation.BrowserPageValidationTests.test_truncated_http_response_fails_closed",
    ),
    (
        "frontend-template-entry-path-check-disabled", "scripts/validate_project_commands.py",
        "and not _safe_template_entry_path(artifact, allow_dot=False)",
        "and False",
        "scripts.test_validate_project_commands.ProjectCommandValidatorTests.test_template_frontend_entry_rejects_non_http_and_escaping_paths",
    ),
    (
        "frontend-entry-file-check-disabled", "scripts/validate_project_commands.py",
        "if entry is not None and not entry.is_file():",
        "if False:",
        "scripts.test_validate_project_commands.ProjectCommandValidatorTests.test_frontend_entry_artifact_must_be_a_file",
    ),
    (
        "swimlane-visible-drilldown-check-disabled", "scripts/swimlane_html_validation.py",
        "if (parser.hidden_entries or parser.hidden_back or modules & (parser.hidden_ids | hidden_css)\n            or \"@unsupported-css-import\" in hidden_css\n            or any(key.startswith((\"@entry:\", \"@back:\")) for key in hidden_css)\n            or any(parser.entry_ids.get(module) in hidden_css for module in modules)\n            or any(parser.entry_tags.get(module) != \"a\" for module in modules)\n            or any(tag != \"a\" for tag in parser.back_tags)\n            or any(parser.entries[module] != f\"#{module}\" or module not in parser.ids for module in modules)):",
        "if any(parser.entries[module] != f\"#{module}\" or module not in parser.ids for module in modules):",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_hidden_drilldown_controls_and_targets_are_rejected",
    ),
    (
        "context-risk-three-segment-check-disabled", "scripts/validate_context_manifest.py",
        "if len(risk_parts) != 3 or any(not part for part in risk_parts):",
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_risk_expansion_requires_exactly_three_segments",
    ),
    (
        "bundle-risk-three-segment-check-disabled", "scripts/validate_delivery_bundle.py",
        "or len(context_risk) != 3\n            or context_risk[:2] != expected_risk",
        "or context_risk[:2] != expected_risk",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_risk_binding_requires_exactly_three_segments",
    ),
    (
        "reuse-source-multiple-evidence-parser-disabled", "scripts/delivery_record_io.py",
        'value.split(",")',
        're.split(r"(?i),|\\s+and\\s+", value)',
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_accepts_delivery_style_and_separated_evidence",
    ),
    (
        "reuse-source-formal-completion-check-disabled", "scripts/reuse_source_run_validation.py",
        "if issues:",
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_applies_formal_completion_semantics",
    ),
    (
        "reuse-source-context-identity-check-disabled", "scripts/reuse_source_run_validation.py",
        '        "Code version": metadata["Code version"],\n',
        "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_binds_current_context_identity_fields",
    ),
    (
        "reuse-source-module-record-binding-disabled", "scripts/reuse_source_run_validation.py",
        '        "Module": module,\n', "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_binds_module_build_and_environment",
    ),
    (
        "reuse-record-module-workset-binding-disabled", "scripts/validate_context_manifest.py",
        'if len(modules) != 1 or source.get("module") != modules[0]:', "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_record_module_must_match_current_workset",
    ),
    (
        "reuse-source-build-environment-binding-disabled", "scripts/reuse_source_run_validation.py",
        '        "Build ID and acceptance environment": f\'{metadata["Build ID"]} / {metadata["Environment ID"]}\',\n', "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_binds_module_build_and_environment",
    ),
    (
        "frontend-click-set-coverage-disabled", "scripts/frontend_state_validation.py",
        "return all(observed[action] for action in ranks) and all(\n        observed[action] == targets[action] for action in ranks\n    )",
        'return all(observed[action] for action in ranks) and all(observed[action] == targets[action] for action in ("navigate", "assert", "screenshot"))',
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_every_declared_click_target_must_be_executed",
    ),
    (
        "frontend-action-computed-state-check-disabled", "scripts/frontend_state_validation.py",
        '                or item.get("visible") is not True or item.get("enabled") is not True\n',
        "",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_action_computed_state_must_be_visible_and_enabled",
    ),
    (
        "swimlane-action-computed-state-check-disabled", "scripts/validate_swimlane_evidence.py",
        '                or item.get("visible") is not True or item.get("enabled") is not True\n',
        "",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_swimlane_action_computed_state_must_be_enabled",
    ),
    (
        "swimlane-interactive-entry-tag-check-disabled", "scripts/swimlane_html_validation.py",
        'or any(parser.entry_tags.get(module) != "a" for module in modules)',
        "or False",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_css_hidden_noninteractive_drilldown_is_rejected",
    ),
    (
        "swimlane-interactive-back-tag-check-disabled", "scripts/swimlane_html_validation.py",
        'or any(tag != "a" for tag in parser.back_tags)',
        "or False",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_noninteractive_back_control_is_rejected",
    ),
    (
        "swimlane-css-hidden-entry-check-disabled", "scripts/swimlane_html_validation.py",
        "hidden_css = css_hidden_ids(styles, parser.elements)",
        "hidden_css = set()",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_css_hidden_drilldown_anchor_is_rejected",
    ),
    (
        "compound-css-selector-check-disabled", "scripts/browser_dom_validation.py",
        "targets = [key for key, attrs in elements.items() if _selector_matches(selector, key, attrs)]",
        "targets = []",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_compound_css_selectors_hide_declared_targets",
    ),
    (
        "css-top-level-selector-list-check-disabled", "scripts/browser_dom_validation.py",
        "for selector in _split_selector_list(selectors):",
        'for selector in selectors.split(","):',
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_css_not_selector_supports_multiple_exclusions",
    ),
    (
        "css-not-selector-check-disabled", "scripts/browser_dom_validation.py",
        "if any(\n        _simple_compound_matches(option.strip(), identity, attrs, unsupported_matches=False)",
        "if False and any(\n        _simple_compound_matches(option.strip(), identity, attrs, unsupported_matches=False)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_css_not_selector_does_not_apply_when_excluded_class_exists",
    ),
    (
        "css-not-disabled-state-check-disabled", "scripts/browser_dom_validation.py",
        'disabled = "disabled" in attrs',
        "disabled = False",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_css_not_disabled_uses_element_state",
    ),
    (
        "swimlane-void-element-stack-check-disabled", "scripts/swimlane_html_validation.py",
        "if tag not in VOID_ELEMENTS:\n            self.hidden_stack.append(hidden)",
        "if True:\n            self.hidden_stack.append(hidden)",
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_hidden_void_element_does_not_hide_following_swimlane_controls",
    ),
    (
        "indexed-png-palette-check-disabled", "scripts/image_evidence_validation.py",
        "if color == 3 and not _valid_palette(chunks):", "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_indexed_png_requires_palette",
    ),
    (
        "frontend-linked-stylesheet-check-disabled", "scripts/browser_dom_validation.py",
        'if kind == "inline":', "if True:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_linked_stylesheet_cannot_hide_declared_targets",
    ),
    (
        "swimlane-linked-stylesheet-check-disabled", "scripts/swimlane_html_validation.py",
        "styles, style_issue = combined_styles(parser.style_sources, evidence, root) if root else (\"\", None)",
        'styles, style_issue = "", None',
        "scripts.test_validate_swimlane_evidence.SwimlaneEvidenceValidatorTests.test_css_combinators_and_linked_styles_hide_drilldown",
    ),
    (
        "frontend-click-sequence-multiplicity-check-disabled", "scripts/frontend_state_validation.py",
        "return all(observed[action] for action in ranks) and all(\n        observed[action] == targets[action] for action in ranks\n    )",
        "return all(observed[action] for action in ranks) and all(set(observed[action]) == set(targets[action]) for action in ranks)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_click_path_order_and_multiplicity_are_exact",
    ),
    (
        "png-unknown-critical-chunk-check-disabled", "scripts/image_evidence_validation.py",
        "if any(kind[0] & 0x20 == 0 and kind not in known_critical for kind, _ in chunks):",
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_png_rejects_unknown_critical_chunks",
    ),
    (
        "reuse-source-module-files-canonicalization-disabled", "scripts/reuse_source_run_validation.py",
        '        and _canonical_csv(fields.get("changed files", "")) == _module_files(\n            metadata["Module changed files"], module,\n        )',
        '        and fields.get("changed files", "") == metadata["Changed files"]',
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_canonicalizes_requirement_and_module_file_order",
    ),
    (
        "reuse-source-requirement-order-canonicalization-disabled", "scripts/reuse_source_run_validation.py",
        '        _canonical_csv(fields.get("traceability ids", "")) == _canonical_csv(metadata["Requirement IDs"])',
        '        fields.get("traceability ids", "") == metadata["Requirement IDs"]',
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_canonicalizes_requirement_and_module_file_order",
    ),
    (
        "css-import-fail-closed-check-disabled", "scripts/browser_dom_validation.py",
        'if "@unsupported-css-import" in hidden_css:', "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_css_import_is_rejected_and_later_visible_rule_wins",
    ),
    (
        "css-cascade-last-rule-check-disabled", "scripts/browser_dom_validation.py",
        "priority = (int(important), _specificity(selector), order, index)",
        "priority = (0, _specificity(selector), order, index)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_css_import_is_rejected_and_later_visible_rule_wins",
    ),
    (
        "png-idat-continuity-check-disabled", "scripts/image_evidence_validation.py",
        "idat_indexes != list(range(min(idat_indexes), max(idat_indexes) + 1))", "False",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_png_idat_chunks_must_be_consecutive",
    ),
    (
        "frontend-click-state-transition-check-disabled", "scripts/validate_frontend_evidence.py",
        'if data.get("state_transitions") != value.get("state_transitions") or not _valid_state_transitions(value):',
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_each_click_requires_a_distinct_asserted_state_transition",
    ),
    (
        "frontend-click-state-artifact-binding-disabled", "scripts/validate_frontend_evidence.py",
        "        _validate_state_transition_artifacts(value, root, issues)\n", "        pass\n",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_state_transition_hashes_must_bind_snapshot_artifacts",
    ),
    (
        "frontend-click-assertion-state-binding-disabled", "scripts/validate_frontend_evidence.py",
        "if before_state is None or after_state is None or not after_state[1] or before_state[0] == after_state[0]:",
        "if False:",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_state_transition_must_change_declared_assertion_dom_state",
    ),
    (
        "frontend-state-visible-text-binding-disabled", "scripts/browser_dom_validation.py",
        "return ((semantic, text), identity not in hidden and identity in parser.visible)",
        "return ((semantic, ''), identity not in hidden and identity in parser.visible)",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_state_transition_accepts_visible_text_change",
    ),
    (
        "frontend-state-unrelated-attribute-filter-disabled", "scripts/browser_dom_validation.py",
        '        or name.startswith("aria-")\n', "        or True\n",
        "scripts.test_validate_frontend_evidence.FrontendEvidenceValidatorTests.test_state_transition_rejects_unrelated_attribute_change",
    ),
    (
        "reuse-source-context-provenance-check-disabled", "scripts/reuse_source_run_validation.py",
        "if not _valid_source_context(source, root, run_id, str(cache_key)):", "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_context_file_must_bind_run_and_cache",
    ),
    (
        "reuse-source-context-field-binding-disabled", "scripts/reuse_source_run_validation.py",
        '        "Context workset manifest and reused evidence fingerprints": f"{source_context_path} / {cache_key}",\n', "",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_run_binds_historical_context_provenance",
    ),
    (
        "reuse-source-context-strict-schema-disabled", "scripts/reuse_source_run_validation.py",
        'if not lines or lines[0] != f"# Context Workset {run_id}" or len(lines) != 3:',
        "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_reuse_source_context_rejects_duplicate_fields",
    ),
    (
        "context-duplicate-workset-path-check-disabled", "scripts/validate_context_manifest.py",
        "if len(paths) != len(set(paths)):", "if False:",
        "scripts.test_validate_context_manifest.ContextManifestValidatorTests.test_duplicate_workset_paths_are_rejected",
    ),
    (
        "public-module-closure-stage-forwarding-disabled",
        "scripts/validate_delivery_bundle.py",
        "        frontend_evidence_path=frontend_evidence_path, stage=stage,\n"
        "        requirement_questions_path=requirement_questions_path,\n"
        "        requirement_questions_sha256=requirement_questions_sha256,\n"
        "        requirement_baseline_version=requirement_baseline_version,\n"
        "        requirement_baseline_sha256=requirement_baseline_sha256,\n"
        "        delivery_contract_path=delivery_contract_path,\n"
        "        allow_passwords=allow_passwords, verifier=None,\n",
        "        frontend_evidence_path=frontend_evidence_path, stage=\"completion\",\n"
        "        requirement_questions_path=requirement_questions_path,\n"
        "        requirement_questions_sha256=requirement_questions_sha256,\n"
        "        requirement_baseline_version=requirement_baseline_version,\n"
        "        requirement_baseline_sha256=requirement_baseline_sha256,\n"
        "        delivery_contract_path=delivery_contract_path,\n"
        "        allow_passwords=allow_passwords, verifier=None,\n",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_closure_candidate_bundle_passes_at_the_planned_stage",
    ),
    (
        "module-scoped-record-template-resolution-disabled", "scripts/delivery_record_paths.py",
        "    return normalize_template(raw_path, context_modules[0], run_id)\n",
        "    return raw_path\n",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_scoped_progress_and_review_templates_pass",
    ),
    (
        "partial-module-record-template-rejection-disabled", "scripts/delivery_record_paths.py",
        "    if not has_module or not has_run_id:\n",
        "    if False:\n",
        "scripts.test_validate_delivery_bundle.DeliveryBundleValidatorTests.test_module_scoped_progress_template_requires_module_and_run_id",
    ),
)
