from __future__ import annotations


MODULE_CLOSURE_MUTANT_CASES = (
    (
        "system-module-requirement-questions-hash-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        "    if questions is None or hashlib.sha256(questions.read_bytes()).hexdigest() != declared:",
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_requirement_questions_hash_drift_fails_closed",
    ),
    (
        "system-module-requirement-closure-forwarding-disabled",
        "scripts/validate_system_delivery_bundle.py",
        '            requirement_questions_path=paths["requirement_questions"],\n',
        "",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_module_validator_receives_requirement_closure_binding",
    ),
    (
        "system-cli-stage-forwarding-disabled",
        "scripts/system_delivery_cli.py",
        '        stage=args.stage, allow_passwords=args.allow_passwords,',
        '        stage="completion", allow_passwords=args.allow_passwords,',
        "scripts.test_flowctl.FlowctlTests.test_process_level_system_close_forwards_explicit_stage",
    ),
    (
        "record-update-module-ownership-check-disabled",
        "scripts/project_record_authorization.py",
        "    if not _target_is_owned(target, owned_paths):",
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_cross_module_m02_writer_cannot_overwrite_m01_record",
    ),
    (
        "record-update-strict-host-lease-verifier-check-disabled",
        "scripts/project_record_authorization.py",
        "    if verifier is None or not _machine_verified(verifier, lease_file, value, host_expected):",
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_strict_security_still_requires_host_attestation",
    ),
    (
        "record-update-current-authority-matrix-check-disabled",
        "scripts/project_record_authorization.py",
        '    if any(issue.severity == "error" for issue in validate_authority_matrix(agents_text)):',
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_mutated_current_authority_matrix_cannot_authorize_write",
    ),
    (
        "record-update-agents-ownership-drift-check-disabled",
        "scripts/project_record_authorization.py",
        '    if value.get("agents_sha256") != agents_sha256:',
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_lease_or_canonical_ownership_drift_fails_closed",
    ),
    (
        "record-update-post-verification-binding-check-disabled",
        "scripts/update_project_record.py",
        "            if not binding_is_current(root, binding):",
        "            if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_lease_change_after_host_verification_fails_before_write",
    ),
    (
        "record-update-exact-lease-binding-disabled",
        "scripts/project_record_authorization.py",
        "    if value != expected:",
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_lease_identity_mismatch_fails_closed",
    ),
    (
        "record-update-registered-writer-binding-disabled",
        "scripts/project_record_authorization.py",
        "    if entry != expected:",
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_delivery_first_rejects_self_selected_dispatcher_identity",
    ),
    (
        "record-update-unique-module-writer-check-disabled",
        "scripts/project_record_authorization.py",
        "    if len(matches) != 1:",
        "    if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_delivery_first_rejects_missing_active_writer_for_module",
    ),
    (
        "record-update-duplicate-registry-identity-check-disabled",
        "scripts/project_record_authorization.py",
        "            if identity in seen[field]:",
        "            if False:",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_delivery_first_rejects_writer_identity_reused_across_modules",
    ),
    (
        "record-update-registry-drift-recheck-disabled",
        "scripts/project_record_authorization.py",
        "        and _current_sha(root, binding.registry_path) == binding.registry_sha256\n",
        "        and True\n",
        "scripts.test_update_project_record.AuthorizedProjectRecordTests.test_registry_change_after_authorization_fails_before_write",
    ),
    (
        "authority-matrix-validator-call-disabled",
        "scripts/agents_policy_validation.py",
        "    issues.extend(validate_authority_matrix(structured))",
        "    issues.extend(())",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_is_required_in_both_root_modes",
    ),
    (
        "authority-matrix-unknown-action-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        '        row.get("action"),',
        '        "route",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_schema_is_closed_and_rows_are_unique",
    ),
    (
        "authority-matrix-row-extra-field-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        "    if not isinstance(row, dict) or tuple(row) != ROW_FIELDS:",
        "    if not isinstance(row, dict):",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_schema_is_closed_and_rows_are_unique",
    ),
    (
        "authority-matrix-prose-override-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        "    if _prose_conflicts(text):",
        "    if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_prose_cannot_override_fixed_denials",
    ),
    (
        "authority-matrix-self-pass-policy-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        '        row.get("policy"),',
        '        "policy-ignored",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_independent_only_cannot_become_self_pass",
    ),
    (
        "authority-matrix-dispatcher-write-policy-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        '        row.get("policy"),',
        '        "policy-ignored",',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_fixed_denials_cannot_be_reauthorized",
    ),
    (
        "authority-matrix-gate-identity-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        '        and proof.get("run_identity") == GATE_PROOF_CONTRACT["run_identity"]',
        "        and True",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_gate_proof_contract_is_exact",
    ),
    (
        "authority-matrix-gate-verdict-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        '        and proof.get("verdict") == "pass"',
        "        and True",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_gate_proof_contract_is_exact",
    ),
    (
        "authority-matrix-gate-receipt-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        "    return all(proof.get(field) == GATE_PROOF_CONTRACT[field] for field in fields)",
        "    return True",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_gate_proof_contract_is_exact",
    ),
    (
        "authority-matrix-hash-binding-check-disabled",
        "scripts/agents_authority_matrix_validation.py",
        "    if _matrix_hash_declared(text) != canonical_matrix_sha256(value):",
        "    if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_authority_matrix_hash_is_bound_by_machine_policy",
    ),
    (
        "dispatcher-free-to-alter-check-disabled", "scripts/agents_dispatcher_policy_validation.py",
        'r"may|can|allowed|permitted|authorized|granted|free to|可以|允许|授权"',
        'r"may|can|allowed|permitted|authorized|granted|可以|允许|授权"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_dispatcher_write_authority_synonyms_are_rejected",
    ),
    (
        "module-closure-opt-out-check-disabled", "scripts/agents_dispatcher_policy_validation.py",
        'r"opt out|need not comply|nonbinding|non-binding|"',
        'r"unused-opt-out-marker|"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_synonym_rule_cannot_discard_module_closure",
    ),
    (
        "maintainer-certify-self-check-disabled", "scripts/agents_self_signoff_policy_validation.py",
        "|certif(?:y|ies|ied|ying)|",
        "|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_synonym_rule_cannot_allow_maintainer_self_signoff",
    ),
    (
        "maintainer-self-closure-synonyms-check-disabled", "scripts/agents_self_signoff_policy_validation.py",
        "clos(?:e|es|ed|ing)|complet(?:e|es|ed|ing)|finali[sz](?:e|es|ed|ing)|review(?:s|ed|ing)?|",
        "review(?:s|ed|ing)?|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_closure_synonyms_cannot_reauthorize_maintainer",
    ),
    (
        "maintainer-complete-finalize-self-closure-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "|complet(?:e|es|ed|ing)|finali[sz](?:e|es|ed|ing)|",
        "|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_complete_and_finalize_cannot_reauthorize_maintainer_self_closure",
    ),
    (
        "action-bound-negation-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'return bool(polarities and polarities[-1].lastgroup == "negative")',
        "return False",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actions_require_action_bound_negation_or_review_condition",
    ),
    (
        "maintainer-independent-review-condition-bypass-restored",
        "scripts/agents_self_signoff_policy_validation.py",
        "return any(not inherited_negation and not _action_is_negated(scope, action.start()) for action in actions)",
        "return False",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_independent_review_condition_reversal_is_rejected_in_both_root_modes",
    ),
    (
        "explicit-actor-rescope-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "matches = tuple(ACTOR_RE.finditer(segment))",
        "matches = tuple(ACTOR_RE.finditer(segment))[:1]",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_explicit_actor_match_starts_scope_without_boundary_enumeration",
    ),
    (
        "maintainer-maintenance-agent-subject-synonym-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "maintenance\\s+Agent|maintainer|",
        "maintainer|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_closure_subject_authority_and_ownership_synonyms_are_rejected",
    ),
    (
        "maintainer-direct-self-closure-default-prohibition-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "return any(not inherited_negation and not _action_is_negated(scope, action.start()) for action in actions)",
        "return False",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actions_require_action_bound_negation_or_review_condition",
    ),
    (
        "dispatcher-module-closure-authority-check-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'if actor == "dispatcher":',
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_direct_self_closure_and_dispatcher_closure_authority_are_rejected",
    ),
    (
        "compound-negative-authority-synonym-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'r"(?P<negative>\\b(?:is\\s+)?not\\s+(?:free|entitled|able|allowed|permitted|authorized|granted)(?:\\s+to)?\\b|"',
        'r"(?P<negative>\\b(?:is\\s+)?not\\s+(?:allowed|permitted|authorized|granted)(?:\\s+to)?\\b|"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actions_require_action_bound_negation_or_review_condition",
    ),
    (
        "action-polarity-reset-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'r"(?P<reset>\\b(?:but|yet|however)\\b|\\b(?:may|can|must|shall|will)\\b|"',
        'r"(?P<reset>\\bnever-reset\\b|"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actions_require_action_bound_negation_or_review_condition",
    ),
    (
        "self-closure-module-ownership-synonym-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "module(?:'s|’s) delivery|",
        "",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_self_closure_subject_authority_and_ownership_synonyms_are_rejected",
    ),
    (
        "implementation-actor-synonyms-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "实现负责人|实现 Agent|授权写者|租约持有人|维护者)",
        "实现负责人|授权写者|租约持有人|维护者)",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actor_and_action_inflections_are_rejected",
    ),
    (
        "action-inflection-normalization-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "accept(?:s|ed|ing)?|",
        "accept|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_fail_closed_actor_and_action_inflections_are_rejected",
    ),
    (
        "controlled-actor-negation-inheritance-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "directly_negated = bool(CONTROL_NEGATION_RE.search(before))",
        "directly_negated = False",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_controlled_actor_inherits_only_action_bound_controller_negation",
    ),
    (
        "controlled-actor-positive-treated-as-negated",
        "scripts/agents_self_signoff_policy_validation.py",
        "directly_negated = bool(CONTROL_NEGATION_RE.search(before))",
        "directly_negated = True",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_controller_negation_must_bind_the_controller_action",
    ),
    (
        "passive-actor-action-binding-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "_passive_scope_allows_prohibited_action(segment)\n        or any",
        "False\n        or any",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_passive_self_closure_is_bound_to_actor_in_both_root_modes",
    ),
    (
        "intrinsic-controller-prohibition-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'if controller.lastgroup in {"intrinsic", "cn_intrinsic"}:',
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_controller_negation_must_bind_the_controller_action",
    ),
    (
        "nominalized-final-authority-action-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "final\\s+approver|",
        "unused-final-approver|",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_nominalized_final_authority_is_an_action_in_both_root_modes",
    ),
    (
        "approval-authority-ownership-relation-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'r"(?P<passive>\\bby|由)|(?P<ownership>\\bbelong(?:s|ed|ing)?\\s+to|归)|"',
        'r"(?P<passive>\\bby|由)|(?P<ownership>unused-ownership-relation)|"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_approval_authority_ownership_is_bound_to_actor_and_delivery",
    ),
    (
        "approval-authority-direct-negation-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "if DIRECT_ACTION_NEGATION_RE.search(scope, 0, action_start):",
        "if False:",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_approval_authority_ownership_is_bound_to_actor_and_delivery",
    ),
    (
        "intrinsic-controller-double-negation-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "return not directly_negated and not CONTROL_FAILURE_RE.search(before)",
        "return True",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_double_negation_and_coordinated_actor_polarity_are_compositional",
    ),
    (
        "coordinated-neither-actor-negation-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        "or _coordinated_actor_negates(segment, matches, index),",
        "or False,",
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_double_negation_and_coordinated_actor_polarity_are_compositional",
    ),
    (
        "negated-prohibition-positive-polarity-disabled",
        "scripts/agents_self_signoff_policy_validation.py",
        'r"(?P<positive>\\b(?:is\\s+)?not\\s+(?:prohibited|forbidden)(?:\\s+(?:from|to))?\\b|"',
        'r"(?P<positive>\\bnever-positive\\b|"',
        "scripts.test_validate_agents_md.ValidatorRegressionTests.test_double_negation_and_coordinated_actor_polarity_are_compositional",
    ),
    (
        "module-maintainer-host-attestation-check-disabled",
        "scripts/implementation_agent_validation.py",
        "    if not validated:",
        "    if False:",
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_module_maintainer_requires_bound_native_sol_receipt",
    ),
    (
        "system-aggregation-writer-role-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        '            or value.get("aggregation_writer_role") != "SYSTEM_AGGREGATION"):',
        "            or False):",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_dispatcher_cannot_author_system_manifest",
    ),
    (
        "system-aggregation-writer-independence-check-disabled",
        "scripts/system_aggregate_validation.py",
        "    if writer_pair[0] in forbidden_agents or writer_pair[1] in forbidden_runs:",
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_aggregation_writer_must_be_independent_of_dispatcher_and_modules",
    ),
    (
        "system-maintainer-agent-uniqueness-check-disabled",
        "scripts/system_aggregate_validation.py",
        "    if len(maintainer_agents) != len(set(maintainer_agents)):",
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_each_module_requires_a_distinct_maintainer_agent_id",
    ),
    (
        "system-global-agent-identity-check-disabled",
        "scripts/system_aggregate_validation.py",
        "    if len(actor_agents) != len(set(actor_agents)) or len(actor_runs) != len(set(actor_runs)):",
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_dispatcher_cannot_reuse_maintainer_agent_with_new_run",
    ),
    (
        "system-dispatcher-host-attestation-check-disabled",
        "scripts/system_actor_validation.py",
        "    issues.extend(_validate_dispatcher(value, root, verifier, state))",
        "    issues.extend(())",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_valid_cross_module_closures_pass_read_only_aggregation",
    ),
    (
        "system-aggregation-output-binding-check-disabled",
        "scripts/system_actor_validation.py",
        '    payload = {key: item for key, item in value.items() if key not in AGGREGATION_RECEIPT_FIELDS}',
        '    payload = {key: item for key, item in value.items() if key not in AGGREGATION_RECEIPT_FIELDS and key != "code_version"}',
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_aggregation_receipt_binds_system_candidate_payload",
    ),
    (
        "system-authority-binding-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        '    if not authority_binding_valid(value.get("authority_binding"), "system"):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_system_authority_binding_missing_or_unknown_row_fails_closed",
    ),
    (
        "module-authority-binding-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        '    if not authority_binding_valid(value.get("authority_binding"), "module"):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_unknown_module_authority_role_action_or_policy_fails_closed",
    ),
    (
        "system-aggregation-authority-receipt-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        '    if not receipt_repeats_authority_binding(path, value.get("authority_binding")):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_aggregation_output_receipt_must_repeat_authority_binding",
    ),
    (
        "effective-agents-authority-reference-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        "    if not agents_declares_authority_binding(\n        agents_text, manifest[\"authority_binding\"],\n    ):",
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_effective_agents_authority_locator_or_sha_drift_fails_closed",
    ),
    (
        "system-gate-identity-revalidation-check-disabled",
        "scripts/validate_system_delivery_bundle.py",
        "    gate_issues, reviewer_agent_ids, reviewer_run_ids = validate_module_gate_actors(\n        evidence, module, root, host_attestation_verifier, stage=stage,\n    )",
        "    gate_issues, reviewer_agent_ids, reviewer_run_ids = [], frozenset(), frozenset()",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_system_revalidates_gate_identity_when_module_validator_is_injected",
    ),
    (
        "gate-output-result-attestation-check-disabled",
        "scripts/native_gate_agent_validation.py",
        '    issues.extend(validate_native_spawn_record(\n'
        '        data=gate,\n'
        '        root=root,\n'
        '        expected=output_expected,\n'
        '        path_field="output_receipt",\n'
        '        hash_field="output_receipt_sha256",\n'
        '        code_prefix="gate-output",\n'
        '        label=f"{role} 独立验收输出",\n'
        '        host_attestation_verifier=host_attestation_verifier,\n'
        '        record_label="output result",\n'
        '        invalid_code="invalid-gate-output-receipt",\n'
        '        receipt_replay_state=receipt_replay_state,\n'
        '    ))',
        '    issues.extend(())',
        "scripts.test_validate_multi_agent_evidence.MultiAgentEvidenceValidatorTests.test_gate_output_tamper_fails_after_project_hash_is_recomputed",
    ),
    (
        "system-aggregation-authority-exact-binding-disabled",
        "scripts/system_actor_validation.py",
        '    expected["authority_binding"] = value.get("authority_binding")',
        '    expected.pop("authority_binding", None)',
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_valid_cross_module_closures_pass_read_only_aggregation",
    ),
    (
        "system-module-gate-pass-recheck-disabled",
        "scripts/system_actor_validation.py",
        '    if any(not isinstance(raw, dict) or raw.get("verdict") != "pass" for raw in gates):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_injected_module_validator_cannot_bypass_gate_fail_verdict",
    ),
    (
        "system-module-closure-recheck-disabled",
        "scripts/system_actor_validation.py",
        '    if (evidence.get("stage") != stage\n            or evidence.get("single_writer_run_id") != evidence.get("implementation_run_id")):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_injected_module_validator_cannot_bypass_open_disagreement_or_stage",
    ),
    (
        "system-module-candidate-format-recheck-disabled",
        "scripts/system_actor_validation.py",
        '    if (not isinstance(candidate_sha256, str) or len(candidate_sha256) != 64\n'
        '            or any(character.lower() not in "0123456789abcdef" for character in candidate_sha256)):',
        "    if False:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_injected_module_validator_cannot_bypass_invalid_candidate_binding",
    ),
    (
        "gate-output-candidate-binding-disabled",
        "scripts/native_gate_agent_validation.py",
        '        "candidate_sha256": evidence.get("candidate_sha256"),',
        '        "candidate_sha256": None,',
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_valid_cross_module_closures_pass_read_only_aggregation",
    ),
    (
        "system-production-test-seam-exposed",
        "scripts/validate_system_delivery_bundle.py",
        "def validate_system_delivery_bundle(\n"
        "    *, manifest_path: Path, project_root: Path, stage: str = \"completion\",\n"
        "    allow_passwords: bool = False,\n"
        ") -> list[Issue]:",
        "def validate_system_delivery_bundle(\n"
        "    *, manifest_path: Path, project_root: Path, stage: str = \"completion\",\n"
        "    allow_passwords: bool = False,\n"
        "    _test_only_module_validator: Callable[..., list[object]] | None = None,\n"
        "    host_attestation_verifier: HostAttestationVerifier | None = None,\n"
        ") -> list[Issue]:",
        "scripts.test_validate_system_delivery_bundle.SystemDeliveryBundleTests.test_production_api_does_not_expose_module_validator_override",
    ),
)
